"""
NASA Standard Breakup Model (SBM) implementation.

Predicts the number, size distribution, and orbital characteristics of
fragments generated by a hypervelocity collision or explosion in orbit.

Based on:
  - Johnson, N.L. et al. (2001). "NASA's New Breakup Model of EVOLVE 4.0"
  - Krisko, P.H. (2011). "Proper Implementation of the 1998 NASA Breakup Model"
  - IADC-04-05: Inter-Agency Space Debris Coordination Committee guidelines

The model distinguishes between:
  1. CATASTROPHIC collision: kinetic energy / target mass > 40 J/g
     → Both objects completely fragment
  2. NON-CATASTROPHIC collision: below 40 J/g threshold
     → Only ejecta from the impact site
  3. EXPLOSION: chemical/electrical (no impactor)
     → Empirical fragment count from historical events

Fragment size distribution follows a power law:
  N(>d) = C × (d/d_ref)^(-α)
where:
  d = characteristic length (meters)
  C = scaling coefficient (depends on total mass and event type)
  α ≈ -1.71 for collisions (EVOLVE 4.0)

Fragment ΔV distribution follows a log-normal in each component.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np


@dataclass
class FragmentCloud:
    """Predicted debris fragment cloud from a breakup event."""

    total_fragments: int  # trackable (>10cm) + lethal (>1cm)
    trackable_fragments: int  # >10cm (radar-trackable)
    lethal_fragments: int  # 1-10cm (lethal but not trackable)
    sub_cm_fragments: int  # <1cm (surface damage only)

    total_mass_kg: float  # total mass in fragments
    largest_fragment_mass_kg: float
    mean_delta_v_m_s: float  # average ejection velocity

    size_distribution: np.ndarray  # (N_bins,) cumulative count vs size
    size_bins_m: np.ndarray  # (N_bins,) characteristic lengths in meters

    orbital_lifetime_years: float  # estimated time for cloud to decay (LEO)
    peak_spatial_density_increase: float  # fractional increase in local debris density


@dataclass
class CollisionConsequence:
    """Full consequence assessment of a potential collision."""

    # Event classification
    event_type: str  # "CATASTROPHIC", "NON_CATASTROPHIC", "EXPLOSION"
    collision_energy_joules: float
    specific_energy_j_per_g: float  # E_kinetic / M_target — threshold is 40 J/g

    # Mass involved
    primary_mass_kg: float
    secondary_mass_kg: float
    combined_mass_kg: float

    # Fragment prediction
    fragment_cloud: FragmentCloud

    # Cascade risk
    kessler_contribution: float  # how much this event accelerates the Kessler syndrome
    # Estimated additional conjunctions per year generated by this debris cloud
    additional_conjunctions_per_year: float


class NASABreakupModel:
    """NASA Standard Breakup Model (EVOLVE 4.0 / ORDEM 3.0).

    Predicts fragment generation from orbital collisions and explosions.
    """

    # Power-law exponent for fragment size distribution (EVOLVE 4.0)
    COLLISION_ALPHA = 1.71    # Johnson 2001 Acta Astronautica 49 25: α = 1.71 for collision
    EXPLOSION_ALPHA = 1.6     # Johnson 2001: α = 1.6 for explosion (slightly flatter distribution)

    # Catastrophic collision threshold (J/g)
    CATASTROPHIC_THRESHOLD_J_PER_G = 40.0  # Johnson 2001 §3: Ec/Mt > 40 J/g → catastrophic

    # Reference characteristic length for scaling
    D_REF_M = 0.01  # 1 cm reference (Johnson 2001 EVOLVE 4.0 §2.1)

    @staticmethod
    def collision_energy(
        mass1_kg: float,
        mass2_kg: float,
        relative_velocity_km_s: float,
    ) -> float:
        """Compute kinetic energy of collision in Joules.

        E = ½ × m_reduced × v_rel²
        For an impactor hitting a target:
        E = ½ × m_impactor × v_rel² (impactor KE in target frame)
        """
        v_m_s = relative_velocity_km_s * 1000.0
        # Use impactor kinetic energy (smaller mass hits larger)
        m_impactor = min(mass1_kg, mass2_kg)
        return 0.5 * m_impactor * v_m_s**2

    @staticmethod
    def is_catastrophic(
        mass_target_kg: float,
        energy_joules: float,
    ) -> bool:
        """Determine if collision is catastrophic (complete fragmentation).

        Catastrophic when specific energy > 40 J/g (40,000 J/kg).
        """
        if mass_target_kg <= 0:
            return True
        specific_energy = energy_joules / (mass_target_kg * 1000)  # J/g
        return specific_energy >= NASABreakupModel.CATASTROPHIC_THRESHOLD_J_PER_G

    @staticmethod
    def fragment_count_catastrophic(
        combined_mass_kg: float,
        min_size_m: float = 0.01,
    ) -> int:
        """Number of fragments larger than min_size from a catastrophic collision.

        NASA SBM formula:
          N(>Lc) = 0.1 × M_total^0.75 × Lc^(-1.71)

        where M_total is in kg, Lc is characteristic length in meters.

        Args:
            combined_mass_kg: Sum of both object masses (kg)
            min_size_m: Minimum characteristic length (m)

        Returns:
            Number of fragments larger than min_size_m
        """
        if combined_mass_kg <= 0 or min_size_m <= 0:
            return 0
        n = 0.1 * (combined_mass_kg**0.75) * (min_size_m**(-1.71))
        return max(0, int(n))

    @staticmethod
    def fragment_count_non_catastrophic(
        impactor_mass_kg: float,
        relative_velocity_km_s: float,
        min_size_m: float = 0.01,
    ) -> int:
        """Fragment count for non-catastrophic (cratering) collision.

        NASA SBM formula:
          N(>Lc) = 0.1 × (M_ejected)^0.75 × Lc^(-1.71)

        where M_ejected ≈ M_impactor × v_rel (empirical scaling).
        """
        v_km_s = relative_velocity_km_s
        m_ejecta = impactor_mass_kg * v_km_s  # empirical mass scaling
        if m_ejecta <= 0 or min_size_m <= 0:
            return 0
        n = 0.1 * (m_ejecta**0.75) * (min_size_m**(-1.71))
        return max(0, int(n))

    @staticmethod
    def fragment_count_explosion(
        total_mass_kg: float,
        min_size_m: float = 0.01,
    ) -> int:
        """Fragment count from an explosion (battery, propellant, etc.).

        Uses slightly different power law (α=1.6 instead of 1.71).
        """
        if total_mass_kg <= 0 or min_size_m <= 0:
            return 0
        n = 0.1 * (total_mass_kg**0.75) * (min_size_m**(-1.6))
        return max(0, int(n))

    @staticmethod
    def size_distribution(
        combined_mass_kg: float,
        event_type: str = "CATASTROPHIC",
        n_bins: int = 50,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Compute cumulative fragment count vs characteristic length.

        Returns:
            (size_bins_m, cumulative_count): arrays of length n_bins
            size_bins_m is log-spaced from 1mm to 10m
        """
        alpha = (NASABreakupModel.COLLISION_ALPHA if event_type != "EXPLOSION"
                 else NASABreakupModel.EXPLOSION_ALPHA)

        sizes = np.logspace(-3, 1, n_bins)  # 1mm to 10m
        coeff = 0.1 * (combined_mass_kg**0.75)
        counts = coeff * sizes**(-alpha)

        # Cap at total mass / minimum fragment mass
        # Minimum fragment mass ≈ 2700 kg/m³ × (4/3)π(d/2)³ for aluminum sphere
        return sizes, np.clip(counts, 0, 1e9).astype(int)

    @staticmethod
    def fragment_delta_v_distribution(
        n_fragments: int,
        event_type: str = "CATASTROPHIC",
        seed: int | None = None,
    ) -> np.ndarray:
        """Generate ΔV distribution for fragments (log-normal).

        Fragment ejection velocities follow a log-normal distribution
        with parameters dependent on fragment size and event type.

        Empirical parameters from EVOLVE 4.0:
          μ_log10 = 0.2 km/s (median ΔV)
          σ_log10 = 0.4 (spread)

        Returns:
            (n_fragments, 3) array of ΔV vectors in km/s (isotropic)
        """
        rng = np.random.default_rng(seed)

        # Log-normal speed distribution
        mu_log = math.log10(0.2)  # median 200 m/s
        sigma_log = 0.4
        speeds = 10**(rng.normal(mu_log, sigma_log, n_fragments))  # km/s

        # Isotropic direction
        cos_theta = rng.uniform(-1, 1, n_fragments)
        sin_theta = np.sqrt(1 - cos_theta**2)
        phi = rng.uniform(0, 2 * np.pi, n_fragments)

        dvx = speeds * sin_theta * np.cos(phi)
        dvy = speeds * sin_theta * np.sin(phi)
        dvz = speeds * cos_theta

        return np.column_stack([dvx, dvy, dvz])

    @staticmethod
    def orbital_lifetime_estimate(altitude_km: float, area_to_mass: float = 0.01) -> float:
        """Rough estimate of debris orbital lifetime in years.

        Based on empirical fits to historical debris decay data.
        Very approximate — depends heavily on solar cycle.

        Args:
            altitude_km: Initial orbital altitude (km)
            area_to_mass: Area-to-mass ratio (m²/kg), typical debris ~0.01

        Returns:
            Estimated orbital lifetime in years
        """
        if altitude_km < 200:
            return 0.01  # days
        elif altitude_km < 400:
            return 1.0 + (altitude_km - 200) / 200 * 4  # 1-5 years
        elif altitude_km < 600:
            return 5 + (altitude_km - 400) / 200 * 20  # 5-25 years
        elif altitude_km < 800:
            return 25 + (altitude_km - 600) / 200 * 75  # 25-100 years
        elif altitude_km < 1000:
            return 100 + (altitude_km - 800) / 200 * 400  # 100-500 years
        else:
            return 1000 + (altitude_km - 1000) * 10  # thousands of years


def mass_from_radius(radius_m: float, density_kg_m3: float = 92.937) -> float:
    """Estimate object mass from radius using empirical density.

    Default density 92.937 kg/m³ is the NASA SBM average for spacecraft
    (much lower than solid aluminum because spacecraft are mostly empty volume).

    For solid debris: use 2700 kg/m³ (aluminum)
    For rocket bodies: use ~50 kg/m³ (thin shell)
    """
    volume = (4.0 / 3.0) * math.pi * radius_m**3
    return density_kg_m3 * volume


def assess_collision_consequence(
    primary_radius_m: float,
    secondary_radius_m: float,
    relative_velocity_km_s: float,
    altitude_km: float,
    primary_mass_kg: float | None = None,
    secondary_mass_kg: float | None = None,
) -> CollisionConsequence:
    """Full collision consequence assessment.

    Given two objects and their encounter parameters, predicts:
      - Whether collision would be catastrophic
      - How many fragments would be generated
      - Size distribution of fragments
      - How long the debris cloud persists
      - Contribution to Kessler syndrome

    Args:
        primary_radius_m: Primary object radius (m)
        secondary_radius_m: Secondary object radius (m)
        relative_velocity_km_s: Relative velocity at TCA (km/s)
        altitude_km: Altitude of conjunction (km)
        primary_mass_kg: Primary mass (estimated from radius if None)
        secondary_mass_kg: Secondary mass (estimated from radius if None)

    Returns:
        CollisionConsequence with full assessment
    """
    model = NASABreakupModel()

    # Estimate masses if not provided
    if primary_mass_kg is None:
        primary_mass_kg = mass_from_radius(primary_radius_m)
    if secondary_mass_kg is None:
        secondary_mass_kg = mass_from_radius(secondary_radius_m)

    combined_mass = primary_mass_kg + secondary_mass_kg
    target_mass = max(primary_mass_kg, secondary_mass_kg)
    impactor_mass = min(primary_mass_kg, secondary_mass_kg)

    # Collision energy
    energy = model.collision_energy(primary_mass_kg, secondary_mass_kg, relative_velocity_km_s)
    specific_energy = energy / (target_mass * 1000) if target_mass > 0 else 0  # J/g

    # Classification
    catastrophic = model.is_catastrophic(target_mass, energy)
    event_type = "CATASTROPHIC" if catastrophic else "NON_CATASTROPHIC"

    # Fragment counts
    if catastrophic:
        n_trackable = model.fragment_count_catastrophic(combined_mass, 0.10)  # >10cm
        n_lethal = model.fragment_count_catastrophic(combined_mass, 0.01) - n_trackable  # 1-10cm
        n_sub_cm = model.fragment_count_catastrophic(combined_mass, 0.001) - n_trackable - n_lethal
        total = n_trackable + n_lethal + n_sub_cm
    else:
        _frag = model.fragment_count_non_catastrophic
        n_trackable = _frag(impactor_mass, relative_velocity_km_s, 0.10)
        n_lethal = _frag(impactor_mass, relative_velocity_km_s, 0.01) - n_trackable
        n_sub_cm = _frag(impactor_mass, relative_velocity_km_s, 0.001) - n_trackable - n_lethal
        total = n_trackable + n_lethal + n_sub_cm

    n_lethal = max(0, n_lethal)
    n_sub_cm = max(0, n_sub_cm)

    # Size distribution
    sizes, counts = model.size_distribution(combined_mass, event_type)

    # Largest fragment: empirical — ~20% of target mass for catastrophic
    largest_frag = target_mass * (0.2 if catastrophic else 0.8)

    # Mean ejection ΔV
    mean_dv = 0.2 if catastrophic else 0.05  # km/s typical

    # Orbital lifetime
    lifetime = model.orbital_lifetime_estimate(altitude_km)

    # Kessler contribution: proportional to trackable fragments × lifetime
    # Normalized so Cosmos-2251/Iridium-33 (2009) ≈ 1.0
    kessler_ref = 2000 * 100  # ~2000 trackable × ~100yr lifetime at 800km
    kessler_contribution = (n_trackable * lifetime) / kessler_ref

    # Additional conjunctions: rough estimate
    # Each trackable fragment in LEO shell generates ~1-5 conjunction warnings/year
    additional_conj = n_trackable * 2.5

    cloud = FragmentCloud(
        total_fragments=total,
        trackable_fragments=n_trackable,
        lethal_fragments=n_lethal,
        sub_cm_fragments=n_sub_cm,
        total_mass_kg=combined_mass * (1.0 if catastrophic else 0.1),
        largest_fragment_mass_kg=largest_frag,
        mean_delta_v_m_s=mean_dv * 1000,
        size_distribution=counts,
        size_bins_m=sizes,
        orbital_lifetime_years=lifetime,
        peak_spatial_density_increase=n_trackable / 1000.0,
    )

    return CollisionConsequence(
        event_type=event_type,
        collision_energy_joules=energy,
        specific_energy_j_per_g=specific_energy,
        primary_mass_kg=primary_mass_kg,
        secondary_mass_kg=secondary_mass_kg,
        combined_mass_kg=combined_mass,
        fragment_cloud=cloud,
        kessler_contribution=kessler_contribution,
        additional_conjunctions_per_year=additional_conj,
    )
