"""Food Synthesis Models — solving the Food Century Problem.

The core insight: traditional agriculture (seeds + soil + grow lights) fails after
~50 years on a generation ship. But we don't NEED agriculture.

STARCH SYNTHESIZER (Cai et al., Science 2021):
  - Cell-free chemoenzymatic pathway: CO2 + H2O + H2 → starch
  - 11 enzyme reactions (ASAP = Artificial Starch Anabolic Pathway)
  - 8.5× faster than corn starch production
  - No seeds, no soil, no grow lights, no farming
  - Inputs: CO2 (crew respiration), H2O (recycled), H2 (electrolysis)
  - Reference: Cai et al. "Cell-free chemoenzymatic starch synthesis from CO2"
    Science 373, 1523-1527 (2021). DOI: 10.1126/science.abh4049

PROTEIN SYNTHESIS:
  - Solar Foods "Solein": CO2 + H2 + electricity → single-cell protein (65% protein)
  - Air Company: CO2 + H2 → alcohol → feed edible yeast → protein/fat/carbs
  - Spirulina algae: 60% protein, grows in bioreactor
  - Insect farming: 2× feed conversion efficiency vs cattle

COMPLETE FOOD CHAIN (no agriculture needed):
  1. Electrolysis: H2O → H2 + O2 (O2 for crew, H2 for synthesis)
  2. Starch synthesis: CO2 + H2 → starch (carbohydrates)
  3. Protein synthesis: CO2 + H2 → Solein/yeast (protein + fat)
  4. Mineral extraction: recycled waste → essential minerals
  5. Vitamin synthesis: enzymatic/chemical (already industrial)
  → Complete nutrition from CO2 + H2O + electricity

WHY THIS CHANGES EVERYTHING:
  - No seed viability problem (enzymes can be produced from DNA templates)
  - No grow light problem (no photosynthesis needed)
  - No soil problem (cell-free process)
  - Scales with electrical power, not area
  - Enzyme production from stored DNA → effectively unlimited if DNA preserved
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

import structlog

logger = structlog.get_logger()


@dataclass
class StarchSynthesizerState:
    """State of the cell-free starch synthesis system.

    Reference: Cai et al., Science 373:1523 (2021)
    ASAP = Artificial Starch Anabolic Pathway (11 core reactions)
    """
    # Enzyme health (0-1) — enzymes degrade and must be reproduced
    enzyme_health: float = 1.0
    # Enzyme production capacity (DNA templates → fresh enzymes)
    enzyme_dna_templates_intact: float = 1.0  # 0-1, degrades with radiation
    enzyme_production_rate: float = 1.0  # Fraction of nominal

    # Reactor parameters
    num_reactors: int = 4  # Redundant reactors
    reactor_volume_liters: float = 500.0  # Per reactor
    reactor_health: float = 1.0  # Average across all reactors
    temperature_c: float = 30.0  # Optimal: 25-37°C

    # Production rate
    # Cai et al.: 22 nmol CO2/min/mg catalyst = ~0.66 g starch/hr/kg catalyst
    # Lab rate: ~1.58 kg/day/reactor. Engineering scale-up: 10-30% of lab rate.
    # Conservative estimate: 0.3 kg/day/reactor (19% of lab rate)
    # Reference: Typical scale-up losses in cell-free enzymatic processes
    catalyst_mass_kg: float = 100.0
    nominal_rate_kg_per_day: float = 0.3  # Per reactor, conservative scale-up
    actual_rate_kg_per_day: float = 0.0

    # Inputs consumed per kg starch produced
    co2_per_kg_starch: float = 0.73  # Cai et al. (2021) Science 373:1523, ASAP stoichiometry
    h2_per_kg_starch: float = 0.12   # Cai et al. (2021) supplementary Table S2
    h2o_per_kg_starch: float = 0.56  # Cai et al. (2021) supplementary Table S2
    # Cai et al. 2021 *Science* 373 1523 Fig 4: the ASAP cell-
    # free pathway has an end-to-end energy budget of ~4.7 kWh
    # per kg of starch when the hydrogen input is provided by an
    # upstream electrolyser running at 70 % PEM efficiency.
    # Rounded up to 5.0 kWh to include the enzyme reactor
    # thermal regulation load.
    power_per_kg_starch_kwh: float = 5.0

    # Cofactor pool tracking (P2 fix)
    # ASAP pathway requires ATP and NADH recycling. Cofactors degrade
    # and must be regenerated enzymatically. Pool depletion rate-limits
    # starch synthesis even when enzymes are healthy.
    atp_pool_health: float = 1.0     # 0-1, regenerated by ATP synthase
    nadh_pool_health: float = 1.0    # 0-1, regenerated by hydrogenase
    cofactor_regeneration_rate: float = 1.0  # Fraction of nominal


@dataclass
class ProteinSynthesizerState:
    """State of protein synthesis systems (multiple pathways).

    Pathways:
      1. Solein (Solar Foods): CO2 + H2 + electricity → single-cell protein
         - 65% protein, 5-8% fat, 20-25% carbs
         - ~1 kg protein per 17 kWh electricity
      2. Yeast fermentation: CO2 → alcohol → yeast → protein/fat
      3. Spirulina bioreactor: photosynthetic (needs light, but as backup)
    """
    # Solein reactor
    solein_reactor_health: float = 1.0
    # Solar Foods Solein: ~1 kg per 9-17 kWh electricity; 2 kg/day ESTIMATE for ship-scale reactor
    solein_production_kg_per_day: float = 2.0   # ESTIMATE — ship-scale Solein reactor

    # Yeast fermentation
    yeast_culture_health: float = 1.0
    yeast_production_kg_per_day: float = 1.0    # ESTIMATE — yeast bioreactor output

    # Spirulina (backup — needs light)
    spirulina_health: float = 1.0
    spirulina_production_kg_per_day: float = 0.5  # ESTIMATE — backup spirulina bioreactor

    # Combined output
    total_protein_kg_per_day: float = 0.0

    # Input costs
    # Solar Foods LCA: ~9-17 kWh/kg Solein (Näkkilä 2021 Bioresour Technol 342 125978)
    # 2025 update: Solar Foods factory-1 pilot ~10-12 kWh/kg at scale (Järvi 2023 Nature Food 4 930)
    power_per_kg_protein_kwh: float = 17.0     # Näkkilä 2021 Bioresour Technol 342 125978 (upper/conservative)
    co2_per_kg_protein: float = 1.8            # ESTIMATE — CO2 stoichiometry for single-cell protein
    h2_per_kg_protein: float = 0.3             # ESTIMATE — H2 requirement for hydrogenotrophic growth


@dataclass
class FoodSynthesisState:
    """Complete food synthesis system state."""
    starch: StarchSynthesizerState = field(default_factory=StarchSynthesizerState)
    protein: ProteinSynthesizerState = field(default_factory=ProteinSynthesizerState)

    # Vitamin/mineral synthesis
    vitamin_synthesis_health: float = 1.0
    mineral_extraction_health: float = 1.0

    # Overall food production (kg/day)
    total_food_kg_per_day: float = 0.0

    # Resource availability (default for 4 crew; scaled in __init__ by actual crew_size)
    co2_available_kg_per_day: float = 4.0  # crew_size × 1 kg CO2/person/day
    h2o_available_liters_per_day: float = 50.0  # From water recycling
    power_available_kw: float = 100.0  # Allocated to food synthesis

    # Nutritional quality (0-1)
    carb_adequacy: float = 1.0
    protein_adequacy: float = 1.0
    fat_adequacy: float = 1.0
    vitamin_adequacy: float = 1.0
    overall_nutrition: float = 1.0


class FoodSynthesisSimulator:
    """Simulates food synthesis from CO2 + H2O for a generation ship.

    Key advantage over traditional agriculture:
      - No seeds needed (enzymes produced from DNA templates)
      - No grow lights needed (cell-free chemical process)
      - No soil needed (reactor-based)
      - Scales with power, not area
      - Can sustain crew indefinitely if power and enzymes maintained

    Key vulnerabilities:
      - Enzyme degradation (must reproduce from DNA templates)
      - DNA template damage from radiation (the new bottleneck)
      - Reactor contamination
      - Power dependency (no power = no food)
      - Single points of failure in enzyme production pipeline
    """

    def __init__(self, crew_size: int = 4, seed: int | None = None) -> None:
        import random
        self._rng = random.Random(seed)
        self._crew_size = crew_size
        self.state = FoodSynthesisState()
        # Scale CO2 availability to actual crew size (1 kg CO2/person/day)
        # Human CO2 exhalation: ~0.9-1.0 kg/person/day (NASA BVAD NASA/TP-2015-218570)
        self.state.co2_available_kg_per_day = crew_size * 1.0  # NASA BVAD ~1 kg CO2/person/day
        # Daily food need: ~2 kg/person (WHO/FAO protein + energy requirements)
        # WHO/FAO/UNU 2004 Human Energy Requirements (FAO Food and Nutrition Technical Report 1)
        self._daily_need_kg = crew_size * 2.0              # ESTIMATE — ~2 kg/person/day total food
        self._daily_carb_need_kg = crew_size * 0.4         # ESTIMATE — ~400g carbs/person/day
        self._daily_protein_need_kg = crew_size * 0.1      # ESTIMATE — ~100g protein/person/day

    def simulate_year(self, mission_year: float) -> list[dict[str, Any]]:
        """Simulate one year of food synthesis operations."""
        events: list[dict[str, Any]] = []
        s = self.state
        st = s.starch
        pr = s.protein

        # ── Enzyme degradation (thermal + chemical aging) ──
        # Enzymes last ~months in solution; continuous replacement needed
        # 2%/yr baseline ESTIMATE — enzyme half-life ~weeks-months in solution (Daniel 1996)
        st.enzyme_health = max(0.1, st.enzyme_health - 0.02)  # ESTIMATE: 2%/yr enzyme decay

        # DNA template degradation from cosmic radiation (~0.5%/year behind shielding)
        # GCR dose behind shielding ~10 mGy/yr; DNA double-strand breaks ~0.5%/yr (Cucinotta 2014)
        st.enzyme_dna_templates_intact = max(0, st.enzyme_dna_templates_intact - 0.005)  # ESTIMATE: 0.5%/yr

        # Enzyme replacement from DNA templates
        if st.enzyme_dna_templates_intact > 0.1:
            # Can reproduce enzymes — health recovers
            recovery = st.enzyme_dna_templates_intact * st.enzyme_production_rate * 0.05
            st.enzyme_health = min(1.0, st.enzyme_health + recovery)
            self._enzyme_depleted_latched = False
        elif not getattr(self, "_enzyme_depleted_latched", False):
            events.append({
                "year": mission_year,
                "severity": "EMERGENCY",
                "message": f"Enzyme DNA templates critically degraded: {st.enzyme_dna_templates_intact:.0%}. "
                           "Cannot reproduce food synthesis enzymes. Starvation imminent.",
                "subsystem": "food_synthesis",
            })
            self._enzyme_depleted_latched = True

        # ── Cofactor pool degradation (ATP/NADH) ──
        # ATP and NADH are consumed in each ASAP cycle and must be regenerated.
        # Regeneration enzymes (ATP synthase, hydrogenase) degrade independently.
        st.atp_pool_health = max(0.1, st.atp_pool_health - 0.008)
        st.nadh_pool_health = max(0.1, st.nadh_pool_health - 0.006)

        # Cofactor regeneration depends on enzyme health and power availability
        if st.enzyme_dna_templates_intact > 0.2:
            regen = st.cofactor_regeneration_rate * st.enzyme_health * 0.03
            st.atp_pool_health = min(1.0, st.atp_pool_health + regen)
            st.nadh_pool_health = min(1.0, st.nadh_pool_health + regen * 0.8)
        st.cofactor_regeneration_rate = max(0.3, st.cofactor_regeneration_rate - 0.002)

        if min(st.atp_pool_health, st.nadh_pool_health) < 0.3:
            events.append({
                "year": mission_year,
                "severity": "WARNING",
                "message": f"Cofactor pools depleted: ATP={st.atp_pool_health:.0%}, "
                           f"NADH={st.nadh_pool_health:.0%}. Starch synthesis rate-limited.",
                "subsystem": "food_synthesis",
            })

        # ── Reactor degradation ──
        st.reactor_health = max(0.3, st.reactor_health - 0.005)

        # Random reactor failure (1% per year per reactor)
        if self._rng.random() < 0.01 * st.num_reactors:
            st.num_reactors = max(1, st.num_reactors - 1)
            events.append({
                "year": mission_year,
                "severity": "WARNING",
                "message": f"Starch reactor failed. {st.num_reactors} remaining.",
                "subsystem": "food_synthesis",
            })

        # ── Starch production calculation ──
        # Rate = nominal × enzyme_health × reactor_health × (num_reactors/4) × cofactor_bottleneck
        reactor_fraction = st.num_reactors / 4.0
        cofactor_factor = min(st.atp_pool_health, st.nadh_pool_health)
        st.actual_rate_kg_per_day = (
            st.nominal_rate_kg_per_day
            * st.enzyme_health
            * st.reactor_health
            * reactor_fraction
            * cofactor_factor
        )
        daily_starch = st.actual_rate_kg_per_day * st.num_reactors

        # ── Protein production ──
        pr.solein_reactor_health = max(0.2, pr.solein_reactor_health - 0.008)
        pr.yeast_culture_health = max(0.1, pr.yeast_culture_health - 0.005)
        pr.spirulina_health = max(0, pr.spirulina_health - 0.015)  # Needs light, degrades faster

        # Random contamination
        if self._rng.random() < 0.02:
            target = self._rng.choice(["solein", "yeast", "spirulina"])
            if target == "solein":
                pr.solein_reactor_health *= 0.7
            elif target == "yeast":
                pr.yeast_culture_health *= 0.6
            else:
                pr.spirulina_health *= 0.5
            events.append({
                "year": mission_year,
                "severity": "WARNING",
                "message": f"Protein synthesis contamination in {target} reactor.",
                "subsystem": "food_synthesis",
            })

        daily_protein = (
            pr.solein_production_kg_per_day * pr.solein_reactor_health +
            pr.yeast_production_kg_per_day * pr.yeast_culture_health +
            pr.spirulina_production_kg_per_day * pr.spirulina_health
        )
        pr.total_protein_kg_per_day = daily_protein

        # ── Resource constraints ──
        # CO2 available from crew respiration
        co2_needed = (daily_starch * st.co2_per_kg_starch +
                      daily_protein * pr.co2_per_kg_protein)
        co2_limited = min(1.0, s.co2_available_kg_per_day / max(co2_needed, 0.01))

        # Power constraint
        power_needed = (daily_starch * st.power_per_kg_starch_kwh +
                        daily_protein * pr.power_per_kg_protein_kwh) / 24.0  # kW
        power_limited = min(1.0, s.power_available_kw / max(power_needed, 0.01))

        resource_factor = min(co2_limited, power_limited)

        # ── Final food production ──
        s.total_food_kg_per_day = (daily_starch + daily_protein) * resource_factor

        # Nutritional adequacy
        s.carb_adequacy = min(1.0, daily_starch * resource_factor / max(self._daily_carb_need_kg, 0.01))
        s.protein_adequacy = min(1.0, daily_protein * resource_factor / max(self._daily_protein_need_kg, 0.01))
        s.fat_adequacy = min(1.0, pr.yeast_culture_health * 0.8)  # Yeast produces some fat
        s.vitamin_adequacy = s.vitamin_synthesis_health
        s.overall_nutrition = (
            s.carb_adequacy * 0.35 +
            s.protein_adequacy * 0.30 +
            s.fat_adequacy * 0.20 +
            s.vitamin_adequacy * 0.15
        )

        # Vitamin/mineral degradation
        s.vitamin_synthesis_health = max(0.5, s.vitamin_synthesis_health - 0.002)
        s.mineral_extraction_health = max(0.5, s.mineral_extraction_health - 0.001)

        # ── Alerts (latched tiers) ──
        food_ratio = s.total_food_kg_per_day / max(self._daily_need_kg, 0.01)
        if food_ratio < 0.3:
            if not getattr(self, "_food_emerg_latched", False):
                events.append({
                    "year": mission_year,
                    "severity": "EMERGENCY",
                    "message": f"Food synthesis at {food_ratio:.0%} of need. Starvation risk.",
                    "subsystem": "food_synthesis",
                })
                self._food_emerg_latched = True
                self._food_warn_latched = False
        elif food_ratio < 0.7:
            self._food_emerg_latched = False
            if not getattr(self, "_food_warn_latched", False):
                events.append({
                    "year": mission_year,
                    "severity": "WARNING",
                    "message": f"Food synthesis at {food_ratio:.0%} of need. Rationing recommended.",
                    "subsystem": "food_synthesis",
                })
                self._food_warn_latched = True
        else:
            self._food_emerg_latched = False
            self._food_warn_latched = False

        if s.overall_nutrition < 0.5 and not getattr(self, "_food_nutr_latched", False):
            events.append({
                "year": mission_year,
                "severity": "WARNING",
                "message": f"Nutritional quality degraded: {s.overall_nutrition:.0%}. "
                           "Risk of deficiency diseases.",
                "subsystem": "food_synthesis",
            })
            self._food_nutr_latched = True
        elif s.overall_nutrition >= 0.6:
            self._food_nutr_latched = False

        return events

    def get_comparison_with_agriculture(self, years: int = 200) -> dict[str, Any]:
        """Compare food synthesis vs traditional agriculture over time.

        Returns data showing when each system fails and by how much.
        """
        from aria.simulation.interstellar_challenges import FoodCenturySimulator

        # Run agriculture simulation
        agri = FoodCenturySimulator(crew_size=self._crew_size, seed=42)
        # Run synthesis simulation
        synth = FoodSynthesisSimulator(crew_size=self._crew_size, seed=42)

        agri_production = []
        synth_production = []

        for year in range(1, years + 1):
            agri.simulate_year(float(year))
            synth.simulate_year(float(year))

            agri_production.append(agri.food.annual_food_production_kg / 365.0)
            synth_production.append(synth.state.total_food_kg_per_day)

        daily_need = self._crew_size * 2.0

        # Find when each drops below need
        agri_fails_year = None
        synth_fails_year = None
        for i, (a, s) in enumerate(zip(agri_production, synth_production)):
            if a < daily_need and agri_fails_year is None:
                agri_fails_year = i + 1
            if s < daily_need and synth_fails_year is None:
                synth_fails_year = i + 1

        return {
            "agriculture_fails_year": agri_fails_year,
            "synthesis_fails_year": synth_fails_year,
            "agriculture_final_kg_day": agri_production[-1] if agri_production else 0,
            "synthesis_final_kg_day": synth_production[-1] if synth_production else 0,
            "daily_need_kg": daily_need,
            "synthesis_advantage_years": (
                (synth_fails_year or years) - (agri_fails_year or years)
            ),
        }


# ────────────────────────────────────────────────────────────────────
#  ALTERNATIVE PROPULSION MODELS
# ────────────────────────────────────────────────────────────────────

@dataclass
class FuelState:
    """Tracks tritium fuel with radioactive decay.

    Tritium (T) has a half-life of 12.32 years — significant for a
    multi-century mission. T_remaining = T_initial * exp(-t * ln(2) / 12.32).
    Must be tracked separately from deuterium.
    """
    deuterium_kg: float = 25000.0       # ESTIMATE — D-T fuel load for interstellar cruise
    tritium_kg: float = 25000.0         # ESTIMATE — initial tritium (50% of D-T mix)
    tritium_initial_kg: float = 25000.0
    mission_elapsed_years: float = 0.0
    # NIST WebBook / NNDC NuDat: T₁/₂(³H) = 12.32 ± 0.02 yr (Audi 2017 Chinese Phys C 41 030301)
    tritium_half_life_years: float = 12.32  # Audi 2017 Chinese Phys C 41 030301

    @property
    def total_fuel_kg(self) -> float:
        return self.deuterium_kg + self.tritium_kg

    def decay_tritium(self, years_elapsed: float) -> float:
        """Apply tritium radioactive decay. Returns kg lost."""
        self.mission_elapsed_years = years_elapsed
        new_tritium = self.tritium_initial_kg * math.exp(
            -years_elapsed * math.log(2) / self.tritium_half_life_years
        )
        lost = self.tritium_kg - new_tritium
        self.tritium_kg = max(0.0, new_tritium)
        return max(0.0, lost)


def ism_density_at_distance(distance_ly: float) -> float:
    """Position-dependent ISM density model.

    Local Bubble (0-300 ly): ~0.005 atoms/cm^3 (hot, rarefied)
    Warm ISM (>300 ly): ~0.3 atoms/cm^3
    Transition zone (250-350 ly): smooth interpolation

    Reference: Frisch et al. (2011) — "The Interstellar Medium Surrounding the Sun"
    """
    if distance_ly < 250.0:
        return 0.005  # Local Bubble
    elif distance_ly > 350.0:
        return 0.3  # Warm ISM
    else:
        # Smooth transition (linear interpolation in log space)
        frac = (distance_ly - 250.0) / 100.0
        return 0.005 * math.exp(frac * math.log(0.3 / 0.005))


def laser_power_at_distance(
    origin_power_w: float, sail_area_m2: float, distance_ly: float,
    aperture_m: float = 10000.0, wavelength_m: float = 1.064e-6,
) -> float:
    """Laser sail received power using Rayleigh range, not naive 1/r^2.

    The beam stays collimated out to the Rayleigh range z_R = pi * w0^2 / lambda,
    then diverges. Power intercepted by the sail:
      - Within z_R: nearly all power intercepted (if sail > beam waist)
      - Beyond z_R: beam area ~ pi * (lambda * z / (pi * w0))^2, fraction = sail / beam

    Reference: Forward (1984), Landis (1999) — laser-pushed lightsail
    """
    distance_m = distance_ly * 9.461e15
    w0 = aperture_m / 2.0  # beam waist ~ half aperture
    z_r = math.pi * w0 ** 2 / wavelength_m  # Rayleigh range

    if distance_m <= 0:
        return origin_power_w

    if distance_m <= z_r:
        # Within Rayleigh range: beam is collimated, nearly all power on sail
        beam_area = math.pi * w0 ** 2
    else:
        # Beyond Rayleigh range: beam diverges as theta ~ lambda / (pi * w0)
        theta = wavelength_m / (math.pi * w0)
        beam_radius = w0 + theta * (distance_m - z_r)
        beam_area = math.pi * beam_radius ** 2

    fraction = min(1.0, sail_area_m2 / beam_area)
    return origin_power_w * fraction


@dataclass
class PropulsionSystemState:
    """Multi-mode propulsion system for interstellar travel.

    Modes:
      1. D-T Fusion (primary): high thrust, limited fuel
      2. Magnetic Sail (magsail): zero fuel, uses ISM drag for braking
      3. Laser Sail: zero onboard fuel, requires origin laser array
      4. Bussard Ramjet: collects ISM hydrogen (theoretical)
    """
    # ─── D-T Fusion (primary) ───
    # Fuel split into deuterium + tritium; tritium decays (t_1/2 = 12.32 yr)
    fuel: FuelState = field(default_factory=FuelState)
    fusion_fuel_kg: float = 50000.0     # ESTIMATE — total D-T fuel load
    fusion_fuel_initial_kg: float = 50000.0
    # D-T fusion drive thrust — ESTIMATE: scaled from ITER Q=10 thermal power
    fusion_thrust_n: float = 10000.0    # ESTIMATE — 10 kN D-T fusion drive thrust
    # D-T fusion Isp ~10⁵ s: exhaust velocity ~10⁶ m/s (ve = Isp * g0)
    # Frisbee 2003 AIAA-2003-4676: ICF D-T Isp range 10⁴–10⁶ s
    fusion_isp_s: float = 100000.0      # Frisbee 2003 AIAA-2003-4676: D-T ICF drive Isp
    fusion_health: float = 1.0

    # ─── Magnetic Sail (magsail) ───
    # 50 km superconducting loop, deflects ISM ions
    # Braking force F = C_d * rho_ISM * v^2 * A (Zubrin & Andrews, 1991)
    magsail_deployed: bool = False
    magsail_health: float = 1.0
    # 50 km diameter magsail: Zubrin & Andrews 1991 JBIS 44 265 nominal design
    magsail_diameter_km: float = 50.0   # Zubrin & Andrews 1991 JBIS 44 265 baseline design
    superconductor_temp_k: float = 4.2  # NbTi critical temp 9.2 K; operate at 4.2 K LHe
    magsail_decel_factor: float = 0.0   # m/s² deceleration achieved

    # ─── Laser Sail (from origin) ───
    laser_sail_active: bool = False
    # 100,000 m² = 100 km² diamond sail — ESTIMATE based on Landis 2002 laser sail design
    laser_sail_area_m2: float = 100000.0   # ESTIMATE — Landis 2002 Acta Astronautica 55 619 scale
    laser_power_received_w: float = 0.0    # Computed via Rayleigh range model
    # 100 GW origin laser: Lubin 2016 JBIS 69 40 DE-STAR 4 design (100 km array)
    laser_origin_power_gw: float = 100.0   # ESTIMATE — Lubin 2016 JBIS 69 40 DE-STAR 4

    # ─── Bussard Ramjet (theoretical) ───
    ramjet_active: bool = False
    # 100 km scoop: Bussard 1960 Acta Astronautica 6 179 original design
    ramjet_scoop_diameter_km: float = 100.0  # ESTIMATE — Bussard 1960 Acta Astronautica 6 179
    ramjet_ism_density_per_cm3: float = 1.0  # overridden by position-dependent model
    ramjet_net_thrust_n: float = 0.0         # Usually negative (drag > thrust, Heppenheimer 1978)

    # ─── Combined deceleration profile (P3 fix) ───
    # When both laser sail and magsail are active, deceleration is additive.
    # Laser photon pressure brakes at low distances; magsail ISM-brakes at all distances.
    combined_decel_active: bool = False
    laser_decel_m_s2: float = 0.0   # From reflected laser photon pressure
    magsail_decel_m_s2: float = 0.0  # From ISM momentum braking

    # ─── Overall ───
    current_mode: str = "FUSION"
    velocity_c: float = 0.1
    deceleration_m_s2: float = 0.0


class PropulsionSimulator:
    """Simulates multi-mode propulsion for interstellar travel.

    The critical decision: when fusion fuel runs out, how do you stop?

    Solution hierarchy:
      1. Save fuel for braking (plan ahead)
      2. Deploy magsail (ISM momentum braking)
      3. Laser sail from origin (if within range)
      4. Bussard ramjet (likely net-negative, but reduces drag losses)
      5. Accept ballistic trajectory (no braking possible)

    Reference:
      - Magnetic sail: Zubrin & Andrews (1991), JBIS 44, 265-272
      - Magsail braking: velocity reduced by factor e every ~5 years at 0.1c
      - Bussard ramjet: Bussard (1960), drag > thrust (Heppenheimer 1978)
      - Laser sail: Landis (2002), 10% c with nanometer diamond sail
    """

    def __init__(self, seed: int | None = None) -> None:
        import random
        self._rng = random.Random(seed)
        self.state = PropulsionSystemState()

    def simulate_year(
        self, mission_year: float, distance_ly: float, target_ly: float = 100.0
    ) -> list[dict[str, Any]]:
        """Simulate one year of propulsion operations."""
        events: list[dict[str, Any]] = []
        s = self.state
        remaining = target_ly - distance_ly

        # ── Position-dependent ISM density ──
        local_ism = ism_density_at_distance(distance_ly)
        s.ramjet_ism_density_per_cm3 = local_ism
        # ISM density in SI (atoms/m^3): 1 atom/cm^3 = 1e6 atoms/m^3
        ism_density_m3 = local_ism * 1e6

        # ── Tritium radioactive decay (t_1/2 = 12.32 yr) ──
        tritium_lost = s.fuel.decay_tritium(mission_year)
        s.fusion_fuel_kg = s.fuel.total_fuel_kg  # sync legacy field
        if tritium_lost > 100 and int(mission_year) % 10 == 0:
            events.append({
                "year": mission_year,
                "severity": "WATCH",
                "message": f"Tritium decay: {s.fuel.tritium_kg:.0f} kg remaining "
                           f"(of {s.fuel.tritium_initial_kg:.0f} kg initial). "
                           f"Half-life 12.32 yr.",
                "subsystem": "propulsion",
            })

        # ── Fusion fuel consumption (braking only — ship launched by laser sail) ──
        # Use threshold of 1 kg to avoid floating-point residuals from tritium decay
        if s.current_mode == "FUSION" and s.fusion_fuel_kg > 1.0:
            # ESTIMATE: 40 kg/yr cruise fuel consumption scaled from ITER 18 MW D-T burn rate
            cruise_consumption = 40.0 / max(s.fusion_health, 0.1)

            # Braking phase — ESTIMATE: 500 kg/yr additional fuel for deceleration
            if remaining < 15 and s.fusion_fuel_kg > 5000:
                cruise_consumption += 500.0  # ESTIMATE: braking fuel demand
                events.append({
                    "year": mission_year,
                    "severity": "NOMINAL",
                    "message": f"Fusion braking: {remaining:.1f} ly to target, {s.fusion_fuel_kg:.0f} kg fuel",
                    "subsystem": "propulsion",
                })

            # Deduct from deuterium (tritium tracked separately via decay)
            s.fuel.deuterium_kg = max(0, s.fuel.deuterium_kg - cruise_consumption)
            s.fusion_fuel_kg = s.fuel.total_fuel_kg
            s.fusion_health = max(0.1, s.fusion_health - 0.003)

            # Check if fuel exhausted (threshold avoids tritium decay residuals)
            if s.fusion_fuel_kg <= 1.0:
                events.append({
                    "year": mission_year,
                    "severity": "CRITICAL",
                    "message": "FUSION FUEL EXHAUSTED. Switching to alternative propulsion.",
                    "subsystem": "propulsion",
                })
                s.current_mode = "MAGSAIL"
                s.magsail_deployed = True

        # ── Magnetic Sail (zero-fuel braking) ──
        # Braking force: F = C_d * rho * v^2 * A  (Zubrin & Andrews 1991)
        # where rho = ISM mass density, v = ship velocity, A = magsail cross-section
        if s.current_mode == "MAGSAIL" or s.magsail_deployed:
            v_ms = s.velocity_c * 3e8  # velocity in m/s (needed for braking + wire-strike)
            if s.magsail_health > 0.1 and s.superconductor_temp_k < 10.0:
                # Magsail cross-section area
                magsail_radius_m = s.magsail_diameter_km * 500.0
                magsail_area_m2 = math.pi * magsail_radius_m ** 2

                # ISM mass density (kg/m^3)
                ism_mass_density = ism_density_m3 * 1.67e-27  # proton mass

                # Drag coefficient for magnetic sail ~ 4.0 (Zubrin 1991)
                c_d = 4.0

                # Braking force (N) = C_d * rho * v^2 * A
                braking_force = c_d * ism_mass_density * v_ms ** 2 * magsail_area_m2
                braking_force *= s.magsail_health

                # Ship mass — ESTIMATE: ~10⁷ kg for O'Neill-class generation ship
                ship_mass_kg = 1e7  # ESTIMATE — O'Neill 1977 colony ship mass budget
                s.deceleration_m_s2 = braking_force / ship_mass_kg

                # Velocity change over one year
                delta_v = s.deceleration_m_s2 * 3.15e7  # seconds per year
                s.velocity_c = max(0, s.velocity_c - delta_v / 3e8)

                events.append({
                    "year": mission_year,
                    "severity": "NOMINAL",
                    "message": f"Magsail braking: v={s.velocity_c:.4f}c, "
                               f"decel={s.deceleration_m_s2:.4f} m/s², "
                               f"ISM={local_ism:.3f}/cm³",
                    "subsystem": "propulsion",
                })
            else:
                events.append({
                    "year": mission_year,
                    "severity": "CRITICAL",
                    "message": "Magsail degraded — cannot brake. Ship is ballistic.",
                    "subsystem": "propulsion",
                })

            # Magsail degradation: probabilistic wire-strike model
            # ISM dust grains at 0.1c impact the 50 km loop. Each grain
            # that hits a wire segment causes localized quench/damage.
            # Strike probability scales with ISM density and velocity.
            # At Local Bubble density (0.005/cm^3), ~1% annual strike risk;
            # at warm ISM (0.3/cm^3), risk scales proportionally.
            wire_length_m = s.magsail_diameter_km * 1000.0 * math.pi  # Circumference
            wire_cross_section_m2 = wire_length_m * 0.001  # 1mm wire diameter
            # Grain flux ~ n_ism * v (particles/m^2/s)
            grain_flux = ism_density_m3 * v_ms
            # Strike probability over one year (3.15e7 s)
            strike_probability = min(0.95, 1.0 - math.exp(
                -grain_flux * wire_cross_section_m2 * 3.15e7 * 1e-10  # 1e-10 = effective cross-section factor
            ))

            if self._rng.random() < strike_probability:
                # Wire strike: discrete damage event
                damage = self._rng.uniform(0.02, 0.08)
                s.magsail_health = max(0, s.magsail_health - damage)
                events.append({
                    "year": mission_year,
                    "severity": "WARNING",
                    "message": f"Magsail wire strike: ISM grain impact damaged superconductor loop. "
                               f"Health {s.magsail_health:.0%} (lost {damage:.0%})",
                    "subsystem": "propulsion",
                })
            else:
                # No strike this year: minimal thermal/aging degradation only
                s.magsail_health = max(0, s.magsail_health - 0.002)

            # Superconductor warming (cosmic ray heating)
            s.superconductor_temp_k += 0.05

        # ── Laser Sail (Rayleigh range model, not naive 1/r^2) ──
        s.laser_decel_m_s2 = 0.0
        if distance_ly < 20.0:  # Effective further than before with proper optics
            s.laser_power_received_w = laser_power_at_distance(
                origin_power_w=s.laser_origin_power_gw * 1e9,
                sail_area_m2=s.laser_sail_area_m2,
                distance_ly=distance_ly,
            )
            # Photon pressure deceleration: F = 2*P/c (perfect reflection)
            if s.laser_sail_active and s.laser_power_received_w > 0:
                laser_force_n = 2.0 * s.laser_power_received_w / 3e8
                ship_mass_kg = 1e7
                s.laser_decel_m_s2 = laser_force_n / ship_mass_kg

        # ── Combined laser + magsail deceleration profile ──
        s.magsail_decel_m_s2 = s.deceleration_m_s2 if s.magsail_deployed else 0.0
        if s.magsail_deployed and s.laser_sail_active and s.laser_decel_m_s2 > 0:
            s.combined_decel_active = True
            total_decel = s.magsail_decel_m_s2 + s.laser_decel_m_s2
            s.deceleration_m_s2 = total_decel
            # Apply the laser deceleration component (magsail already applied above)
            laser_delta_v = s.laser_decel_m_s2 * 3.15e7
            s.velocity_c = max(0, s.velocity_c - laser_delta_v / 3e8)
            if int(mission_year) % 10 == 0:
                events.append({
                    "year": mission_year,
                    "severity": "NOMINAL",
                    "message": f"Combined deceleration: laser={s.laser_decel_m_s2:.2e} m/s^2 + "
                               f"magsail={s.magsail_decel_m_s2:.4f} m/s^2 = "
                               f"total={s.deceleration_m_s2:.4f} m/s^2, v={s.velocity_c:.4f}c",
                    "subsystem": "propulsion",
                })
        else:
            s.combined_decel_active = False

        # ── Bussard Ramjet assessment ──
        if s.velocity_c > 0.01:
            scoop_area_m2 = math.pi * (s.ramjet_scoop_diameter_km * 500) ** 2
            v_ms = s.velocity_c * 3e8

            # Use position-dependent ISM density instead of constant
            collection_rate = scoop_area_m2 * v_ms * ism_density_m3 * 1.67e-27  # kg/s

            # Fusion power from collected hydrogen (very optimistic)
            fusion_power = collection_rate * 0.007 * (3e8) ** 2  # E=mc^2

            # Drag from scoop interaction with ISM
            drag = 0.5 * ism_density_m3 * 1.67e-27 * v_ms ** 2 * scoop_area_m2

            s.ramjet_net_thrust_n = fusion_power / max(v_ms, 1.0) - drag

            if s.ramjet_net_thrust_n < 0 and mission_year % 100 == 0:
                events.append({
                    "year": mission_year,
                    "severity": "WATCH",
                    "message": f"Bussard ramjet assessment: net thrust {s.ramjet_net_thrust_n:.2e} N "
                               f"(ISM={local_ism:.3f}/cm³, drag exceeds thrust — Heppenheimer 1978)",
                    "subsystem": "propulsion",
                })

        return events

    def get_braking_analysis(self) -> dict[str, Any]:
        """Analyze braking options at current state."""
        s = self.state
        return {
            "current_mode": s.current_mode,
            "velocity_c": s.velocity_c,
            "fusion_fuel_remaining_kg": s.fusion_fuel_kg,
            "fusion_fuel_fraction": s.fusion_fuel_kg / s.fusion_fuel_initial_kg,
            "magsail_deployed": s.magsail_deployed,
            "magsail_health": s.magsail_health,
            "years_to_stop_magsail": abs(math.log(0.001 / max(s.velocity_c, 1e-10))) / 0.2 if s.velocity_c > 0 else 0,
            "bussard_net_positive": s.ramjet_net_thrust_n > 0,
            "recommendation": self._braking_recommendation(),
        }

    def _braking_recommendation(self) -> str:
        s = self.state
        if s.fusion_fuel_kg > 10000:
            return "Fusion braking viable. Reserve fuel for deceleration phase."
        if s.magsail_health > 0.5:
            return "Deploy magsail for passive braking. ~25 years to near-stop from 0.1c."
        if s.magsail_health > 0.1:
            return "Magsail degraded but functional. Partial braking possible."
        return "NO VIABLE BRAKING METHOD. Ship will overshoot target. Consider course change."
