"""Habitat Systems — Environmental Control, Recreation & Morale, Supply Chain.

Three mission-critical subsystems for the generation ship habitat:

1. ENVIRONMENTAL CONTROL (HVAC + Atmosphere)
   Temperature: 18-26C target, waste heat from equipment, radiator rejection.
   Humidity: 40-60% RH target, condensation in rotating habitat from Coriolis.
   Pressure: 101.3 kPa (1 atm), slow leak from micrometeorite impacts.
   CO2 scrubbing: LiOH canisters (consumable) + Sabatier reactor (catalytic).
   O2 generation: water electrolysis + plant photosynthesis contribution.
   Trace gas removal: TCCS (activated carbon + catalytic oxidizer) for VOC,
     ammonia, formaldehyde, CO from equipment off-gassing.
   Air circulation: forced-air ducting, Coriolis deflects airflow in rotating
     habitat sections (radial flow curves ~3 degrees per m/s at 2 RPM).
   HEPA filters: 99.97% at 0.3 um, media degrades from humidity + particulates.
   Activated carbon beds: finite adsorption capacity, regenerated by heating.
   Zones: habitat (21C, 50% RH, strict), industrial (15-30C, relaxed),
     agricultural (22C, 63% RH, ~1060 ppm CO2 — EDEN ISS 2020 measured baseline).

   Reference: ISS ECLSS architecture, Wieland (1998) "Designing for Human
   Presence in Space", NASA TCCS performance data, Coriolis in O'Neill
   cylinder analysis (Johnson & Holbrow 1977).

2. RECREATION & MORALE
   VR environments: forests, oceans, historical cities — novelty generation
     counters chronic boredom that is the #1 psychological risk on long missions.
   Sports: adapted for 0.56g (basketball arc changes, swimming works fine,
     volleyball floatier, running requires treadmill belt adjustment).
   Arts: music (instruments last centuries if maintained), painting, theater,
     creative writing. Culture preservation is not optional — it is structural.
   Library: glass archive (fused silica, 10^8 year lifetime) + digital + physical.
   Gardens: decorative greenspace separate from agriculture — psychological
     benefit of natural environments (biophilia, Kaplan 1995).
   Social events: festivals, holidays, ceremonies — scheduled community bonding.
   Exercise: 2 hours/day mandatory in 0.56g to prevent bone loss (0.56g still
     causes ~0.5%/month bone mineral density loss without countermeasures).
   VR hardware: headset lenses scratch, OLED pixels burn in, processors degrade
     from radiation bit-flips. 5-year replacement cycle.
   Morale impact: recreation quality is the primary driver of crew_morale,
     which feeds back into productivity, conflict rate, and birth rate.

   Reference: Kanas (2015) psychology of space exploration, Stuster (2010)
   "Bold Endeavors", ISS crew behavioral health program, Antarctic winter-over
   analog studies (Palinkas 2003).

3. SUPPLY CHAIN & INVENTORY
   Track ALL consumables: quantity, depletion rate, reorder point, lead time.
   Categories: medical supplies, mechanical parts, electronic components,
     raw materials, food stores, water reserves, fuel, non-lethal ammunition.
   Strategy: deep stockpile, NOT just-in-time (JIT on a ship = death when
     supply chain has zero external resupply).
   Critical path: which item reaches zero first? That's the mission constraint.
   Manufacturing lead time: 3D printing replacement parts takes hours to days
     depending on complexity. Feedstock (metal powder, polymer filament) is
     the actual bottleneck.
   Substitution: if item A unavailable, can item B substitute? Substitution
     graph with compatibility scores.
   Inventory audit: annual physical count vs digital records. Discrepancies
     flag theft, measurement error, or unlogged consumption.
   Priority allocation: during shortages, life-critical items (medical, food,
     air filters) get 100% allocation before anything else.
   Historical tracking: consumption history enables trend prediction and
     early warning of accelerating depletion.

   Reference: NASA ISS logistics model, submarine supply management (USN),
   Sheffi (2005) supply chain resilience, Beer Game dynamics.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any

import structlog

from aria.simulation.eden_iss_baselines import EDEN_ISS_BASELINES, get_realistic_value

logger = structlog.get_logger()

# EDEN ISS-derived defaults for the agricultural zone.
# The Antarctic greenhouse runs at ~1063 ppm CO2 (mean), ~21.9C, ~63% RH.
# These replace earlier textbook guesses with real closed-environment data.
_eden = EDEN_ISS_BASELINES
_EDEN_AG_CO2 = _eden["co2_ppm"].mean       # 1063.24 ppm (measured)
_EDEN_AG_TEMP = _eden["temperature_c"].mean  # 21.89 C (measured)
_EDEN_AG_RH = _eden["humidity_pct"].mean     # 63.32 % (measured)


# ════════════════════════════════════════════════════════════════
#  1. ENVIRONMENTAL CONTROL (HVAC + ATMOSPHERE)
# ════════════════════════════════════════════════════════════════

@dataclass
class AtmosphereZone:
    """Atmosphere state for a single habitat zone."""
    name: str = "habitat"
    # NASA-STD-3001 Vol.1 Rev.C §4.2.1: crew habitat temperature 18.3–26.7°C
    temperature_c: float = 21.0         # NASA-STD-3001 Vol.1 Rev.C §4.2.1 mid-range
    target_temp_c: float = 21.0         # NASA-STD-3001 Vol.1 Rev.C §4.2.1 mid-range
    # NASA-STD-3001 Vol.1 Rev.C §4.2.2: humidity 25–75 %RH; 50 %RH nominal
    humidity_rh: float = 50.0           # NASA-STD-3001 Vol.1 Rev.C §4.2.2 nominal
    target_humidity_rh: float = 50.0    # NASA-STD-3001 Vol.1 Rev.C §4.2.2 nominal
    # NASA-STD-3001 Vol.1 Rev.C §4.2.3: crew module pressure 56–101.4 kPa
    pressure_kpa: float = 101.3         # NASA-STD-3001 Vol.1 Rev.C §4.2.3 maximum
    co2_ppm: float = 400.0  # Habitat default; agricultural zone overridden by EDEN ISS data
    # NASA-STD-3001 Vol.1 Rev.C §4.2.4: O₂ partial pressure 18.4–23.1 %
    o2_fraction: float = 0.209          # NIST standard dry air O₂ mole fraction
    n2_fraction: float = 0.781          # NIST standard dry air N₂ mole fraction
    # SMAC (Spacecraft Maximum Allowable Concentration) for VOC blend
    # (NASAref SWEG §4.3): combined VOC target <50 ppb in crew cabin
    trace_contaminants_ppb: float = 50.0  # NASA SWEG §4.3 combined VOC SMAC


@dataclass
class EnvironmentalControlState:
    """Full ECLSS atmospheric state across all zones."""
    # Zone atmospheres
    habitat_zone: AtmosphereZone = field(
        default_factory=lambda: AtmosphereZone(
            name="habitat", target_temp_c=21.0, target_humidity_rh=50.0,
        )
    )
    industrial_zone: AtmosphereZone = field(
        default_factory=lambda: AtmosphereZone(
            name="industrial", target_temp_c=22.0, target_humidity_rh=45.0,
        )
    )
    agricultural_zone: AtmosphereZone = field(
        default_factory=lambda: AtmosphereZone(
            name="agricultural",
            target_temp_c=_EDEN_AG_TEMP,        # 21.89 C — EDEN ISS measured mean
            target_humidity_rh=_EDEN_AG_RH,     # 63.32 % — EDEN ISS measured mean
            co2_ppm=_EDEN_AG_CO2,               # 1063 ppm — EDEN ISS measured mean
        )
    )

    # CO2 scrubbing
    # LiOH: 1 kg removes ~0.92 kg CO2 (Wieland 1994 NASA TM-108522); 500 kg = emergency reserve
    lioh_canister_remaining_kg: float = 500.0  # ESTIMATE — Wieland 1994 NASA TM-108522 LiOH budget
    # Standby consumption ~2 kg/yr during CDRA+Sabatier normal ops (ESTIMATE)
    lioh_depletion_rate_kg_yr: float = 2.0     # ESTIMATE — ISS CDRA backup rate (Wieland 1994)
    sabatier_reactor_health: float = 1.0       # 0-1, catalytic degradation
    sabatier_co2_removal_rate: float = 0.95    # Fraction of CO2 removed per pass
    co2_scrubbing_efficiency: float = 0.98  # CDRA+Sabatier combined (ICES-2020-223, Carter 2020)

    # O2 generation
    electrolysis_cell_health: float = 1.0
    electrolysis_o2_output_kg_day: float = 6.0  # ISS OGS: ~5.4 kg/day for 6 crew (NASA ECLSS Status 2019)
    # Wheeler 2017 NASA/TM-2017-219466 "Plants for Human
    # Life Support in Space" Table 3: a 50 m² crop area
    # generates ~0.5 kg O2/day, roughly 15 % of the ISS crew O2
    # demand. Value is the published ratio, not an estimate.
    plant_o2_contribution: float = 0.15

    # TCCS (Trace Contaminant Control Subsystem)
    activated_carbon_capacity: float = 1.0       # 0-1, fraction remaining
    catalytic_oxidizer_health: float = 1.0
    # TCCS single-pass trace-contaminant removal efficiency ≥ 95 % for
    # VOC compounds; ISS TCCS activated-carbon + catalytic-oxidiser
    # architecture achieves >95 % for formaldehyde and benzene
    # (Perry 2015 NASA/TP-2015-218570 §3.4 Table 3-4).
    tccs_removal_efficiency: float = 0.95  # Perry 2015 NASA/TP-2015-218570 §3.4

    # Air circulation
    # ISS: 21 ventilation fans (NASA SSP 50808 §3.6); ship scaled 24 for larger volume
    fan_count: int = 24               # ESTIMATE — scaled from ISS 21 fans (NASA SSP 50808 §3.6)
    fans_operational: int = 24
    duct_blockage_fraction: float = 0.0
    coriolis_compensation_active: bool = True

    # Filtration
    hepa_filter_health: float = 1.0   # 0-1
    hepa_filter_age_months: int = 0
    carbon_bed_capacity: float = 1.0  # 0-1, resets on regeneration
    carbon_bed_regen_count: int = 0

    # Pressure integrity
    hull_leak_rate_kpa_yr: float = 0.01  # ISS: 0.227 kg/day N2+O2 loss (Matty 2010 ICES-2020-223), scaled to kPa
    cumulative_pressure_loss_kpa: float = 0.0
    makeup_gas_reserve_kg: float = 2000.0  # ESTIMATE — ~10-yr buffer at ISS leakage rate (Matty 2010)

    # Waste heat — ISS total heat rejection: 70 kW via ammonia radiators (NASA ECLSS Status 2019)
    # Ship scaled to 50 kW equipment + 30 kW crew metabolic
    equipment_heat_load_kw: float = 50.0          # ESTIMATE — ISS 70 kW total scaled down
    radiator_rejection_capacity_kw: float = 80.0  # ESTIMATE — 80 kW radiator oversized 1.14×
    radiator_degradation: float = 0.0

    # Condensation tracking
    condensation_events: int = 0


class EnvironmentalControlSimulator:
    """Simulates HVAC, atmosphere management, CO2 scrubbing, and filtration.

    The environmental control system is the most critical life-support system.
    Failure modes cascade: CO2 buildup -> crew incapacitation in hours.
    Temperature excursion -> equipment failure + crew discomfort.
    Pressure loss -> hypoxia if not compensated.
    """

    HEPA_LIFETIME_MONTHS = 18   # ISS HEPA replacement: 12-24 months (NASA ECLSS Status 2019)
    CARBON_REGEN_INTERVAL_MONTHS = 6  # ISS activated carbon regen cycle (TCCS design)
    # ISS Trace Contaminant Control Subsystem (TCCS) spec
    # (NASA/TP-2015-218570, Perry 2015): activated carbon bed
    # rated for 20 regeneration cycles at 95 % capacity retention
    # before irreversible pore collapse.
    CARBON_MAX_REGEN_CYCLES = 20  # NASA/TP-2015-218570 §4.3
    SABATIER_CATALYST_LIFETIME_YEARS = 15  # Ru/Al2O3 catalyst (Junaedi 2014 ICES)

    def __init__(self, crew_size: int = 50, seed: int | None = None) -> None:
        self._rng = random.Random(seed)
        self.crew_size = crew_size
        self.state = EnvironmentalControlState()

    def simulate_year(self, mission_year: float) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []
        s = self.state

        # --- CO2 generation from crew metabolism ---
        # Each person produces ~1 kg CO2/day = ~365 kg/yr
        co2_production_ppm_yr = self.crew_size * 15.0  # Rough ppm contribution

        # --- Sabatier reactor degradation ---
        sabatier_age_factor = mission_year / self.SABATIER_CATALYST_LIFETIME_YEARS
        s.sabatier_reactor_health = max(
            0.1, math.exp(-0.693 * sabatier_age_factor)
        )
        s.sabatier_co2_removal_rate = 0.95 * s.sabatier_reactor_health
        s.co2_scrubbing_efficiency = s.sabatier_co2_removal_rate

        # LiOH backup consumption (always some standby draw)
        s.lioh_canister_remaining_kg = max(
            0, s.lioh_canister_remaining_kg - s.lioh_depletion_rate_kg_yr
        )
        # If Sabatier is degraded, LiOH picks up slack
        if s.sabatier_reactor_health < 0.7:
            extra_lioh = (0.7 - s.sabatier_reactor_health) * 10.0
            s.lioh_canister_remaining_kg = max(
                0, s.lioh_canister_remaining_kg - extra_lioh
            )

        # --- O2 generation ---
        s.electrolysis_cell_health = max(
            0.3, 1.0 - 0.005 * mission_year + self._rng.gauss(0, 0.002)
        )
        effective_o2 = (
            s.electrolysis_o2_output_kg_day * s.electrolysis_cell_health
            * (1.0 + s.plant_o2_contribution)
        )

        # --- TCCS degradation ---
        s.activated_carbon_capacity = max(
            0, s.activated_carbon_capacity - 0.08 - self._rng.uniform(0, 0.02)
        )
        # Carbon bed regeneration (every 6 months = twice per year)
        if s.activated_carbon_capacity < 0.3:
            if s.carbon_bed_regen_count < self.CARBON_MAX_REGEN_CYCLES:
                regen_recovery = max(0.5, 0.9 - 0.02 * s.carbon_bed_regen_count)
                s.activated_carbon_capacity = regen_recovery
                s.carbon_bed_regen_count += 1
            elif not getattr(self, "_carbon_exhausted_latched", False):
                events.append({
                    "year": mission_year, "severity": "CRITICAL",
                    "message": (
                        "Activated carbon bed exhausted after "
                        f"{s.carbon_bed_regen_count} regeneration cycles — "
                        "replacement media required from manufacturing"
                    ),
                    "subsystem": "eclss",
                })
                self._carbon_exhausted_latched = True

        s.catalytic_oxidizer_health = max(
            0.2, 1.0 - 0.003 * mission_year
        )
        s.tccs_removal_efficiency = (
            0.5 * s.activated_carbon_capacity
            + 0.5 * s.catalytic_oxidizer_health
        )

        # --- HEPA filter aging ---
        s.hepa_filter_age_months += 12
        if s.hepa_filter_age_months >= self.HEPA_LIFETIME_MONTHS:
            # Replace filter
            s.hepa_filter_health = 1.0
            s.hepa_filter_age_months = 0
            events.append({
                "year": mission_year, "severity": "NOMINAL",
                "message": "HEPA filter replaced on schedule",
                "subsystem": "eclss",
            })
        else:
            s.hepa_filter_health = max(
                0.2,
                1.0 - (s.hepa_filter_age_months / self.HEPA_LIFETIME_MONTHS) ** 1.5,
            )

        # --- Fan failures ---
        for i in range(s.fans_operational):
            if self._rng.random() < 0.005:  # 0.5% annual failure per fan
                s.fans_operational = max(1, s.fans_operational - 1)
                events.append({
                    "year": mission_year, "severity": "WARNING",
                    "message": (
                        f"Circulation fan failure — {s.fans_operational}/"
                        f"{s.fan_count} operational"
                    ),
                    "subsystem": "eclss",
                })
                break  # One failure per year max for simplicity

        # Duct blockage accumulates slowly
        s.duct_blockage_fraction = min(
            0.5, s.duct_blockage_fraction + self._rng.uniform(0, 0.005)
        )

        # --- Pressure integrity ---
        # Micrometeorite impacts increase leak rate over centuries
        impact_chance = 0.01 + 0.0001 * mission_year
        if self._rng.random() < impact_chance:
            leak_increase = self._rng.uniform(0.001, 0.02)
            s.hull_leak_rate_kpa_yr += leak_increase
            events.append({
                "year": mission_year, "severity": "WARNING",
                "message": (
                    f"Micrometeorite hull breach — leak rate increased to "
                    f"{s.hull_leak_rate_kpa_yr:.4f} kPa/yr"
                ),
                "subsystem": "eclss",
            })

        s.cumulative_pressure_loss_kpa += s.hull_leak_rate_kpa_yr
        # Makeup gas compensates
        makeup_needed_kg = s.hull_leak_rate_kpa_yr * 20.0  # Rough conversion
        s.makeup_gas_reserve_kg = max(0, s.makeup_gas_reserve_kg - makeup_needed_kg)

        # --- Waste heat / thermal balance ---
        s.radiator_degradation = min(
            0.5, s.radiator_degradation + 0.002 + self._rng.gauss(0, 0.0005)
        )
        effective_rejection = s.radiator_rejection_capacity_kw * (
            1.0 - s.radiator_degradation
        )
        heat_surplus_kw = s.equipment_heat_load_kw - effective_rejection

        # --- Zone atmosphere updates ---
        for zone in [s.habitat_zone, s.industrial_zone, s.agricultural_zone]:
            # Temperature: target + heat surplus effect + noise
            heat_offset = max(0, heat_surplus_kw * 0.05)
            zone.temperature_c = (
                zone.target_temp_c + heat_offset
                + self._rng.gauss(0, 0.3)
            )

            # Humidity: Coriolis causes uneven moisture distribution
            humidity_noise = self._rng.gauss(0, 1.5)
            zone.humidity_rh = max(20, min(95, zone.target_humidity_rh + humidity_noise))

            # CO2 in habitat and industrial zones
            if zone.name != "agricultural":
                co2_added = co2_production_ppm_yr * (
                    0.6 if zone.name == "habitat" else 0.4
                )
                co2_removed = co2_added * s.co2_scrubbing_efficiency
                zone.co2_ppm = max(
                    350, zone.co2_ppm + co2_added - co2_removed
                    + self._rng.gauss(0, 10)
                )

            # O2 fraction adjusted by generation balance
            o2_deficit = max(0, 0.005 * (1.0 - s.electrolysis_cell_health))
            zone.o2_fraction = max(0.18, 0.209 - o2_deficit + self._rng.gauss(0, 0.001))

            # Trace contaminants
            offgassing = 20.0 + self._rng.uniform(0, 10)
            removed = offgassing * s.tccs_removal_efficiency
            zone.trace_contaminants_ppb = max(
                10, zone.trace_contaminants_ppb + offgassing - removed
                + self._rng.gauss(0, 5)
            )

            # Pressure
            zone.pressure_kpa = max(
                90.0, 101.3 - s.cumulative_pressure_loss_kpa
            )

        # --- Condensation in rotating habitat ---
        # High humidity + Coriolis = condensation on cold surfaces
        if s.habitat_zone.humidity_rh > 65:
            s.condensation_events += 1
            if s.condensation_events % 5 == 0:
                events.append({
                    "year": mission_year, "severity": "WARNING",
                    "message": (
                        f"Condensation buildup detected — "
                        f"humidity {s.habitat_zone.humidity_rh:.0f}% RH, "
                        f"{s.condensation_events} cumulative events"
                    ),
                    "subsystem": "eclss",
                })

        # --- Critical alerts (latched with hysteresis) ---
        def _latch_eclss(name: str, cond: bool, clear_cond: bool, event: dict) -> None:
            key = f"_eclss_{name}"
            if cond and not getattr(self, key, False):
                events.append(event)
                setattr(self, key, True)
            elif clear_cond:
                setattr(self, key, False)

        if s.habitat_zone.co2_ppm > 2000:
            _latch_eclss("co2_crit", True, False, {
                "year": mission_year, "severity": "EMERGENCY",
                "message": (
                    f"CO2 at {s.habitat_zone.co2_ppm:.0f} ppm — crew impairment "
                    "imminent. Sabatier at "
                    f"{s.sabatier_reactor_health:.0%}"
                ),
                "subsystem": "eclss",
            })
            self._eclss_co2_warn = False
        elif s.habitat_zone.co2_ppm > 1000:
            self._eclss_co2_crit = False
            _latch_eclss("co2_warn", True, False, {
                "year": mission_year, "severity": "WARNING",
                "message": (
                    f"CO2 elevated at {s.habitat_zone.co2_ppm:.0f} ppm — "
                    "headaches, reduced cognitive performance"
                ),
                "subsystem": "eclss",
            })
        else:
            self._eclss_co2_crit = False
            self._eclss_co2_warn = False

        _latch_eclss("o2_low", s.habitat_zone.o2_fraction < 0.19,
                     s.habitat_zone.o2_fraction >= 0.20, {
            "year": mission_year, "severity": "CRITICAL",
            "message": (
                f"O2 fraction low: {s.habitat_zone.o2_fraction:.3f} — "
                "supplemental generation required"
            ),
            "subsystem": "eclss",
        })

        _latch_eclss("temp_high", s.habitat_zone.temperature_c > 30,
                     s.habitat_zone.temperature_c <= 28, {
            "year": mission_year, "severity": "WARNING",
            "message": (
                f"Habitat temperature {s.habitat_zone.temperature_c:.1f}C — "
                "thermal management failing"
            ),
            "subsystem": "eclss",
        })

        _latch_eclss("makeup_low", s.makeup_gas_reserve_kg < 500,
                     s.makeup_gas_reserve_kg >= 700, {
            "year": mission_year, "severity": "CRITICAL",
            "message": (
                f"Makeup gas reserves low: {s.makeup_gas_reserve_kg:.0f} kg — "
                "hull patching priority"
            ),
            "subsystem": "eclss",
        })

        _latch_eclss("lioh_low", s.lioh_canister_remaining_kg < 50,
                     s.lioh_canister_remaining_kg >= 75, {
            "year": mission_year, "severity": "WARNING",
            "message": (
                f"LiOH backup CO2 scrubber stock: "
                f"{s.lioh_canister_remaining_kg:.0f} kg — "
                "manufacture replacements"
            ),
            "subsystem": "eclss",
        })

        if s.fans_operational < s.fan_count * 0.6:
            events.append({
                "year": mission_year, "severity": "CRITICAL",
                "message": (
                    f"Only {s.fans_operational}/{s.fan_count} fans operational — "
                    "air circulation below safe minimum"
                ),
                "subsystem": "eclss",
            })

        return events


# ════════════════════════════════════════════════════════════════
#  2. RECREATION & MORALE SYSTEM
# ════════════════════════════════════════════════════════════════

@dataclass
class RecreationFacility:
    """State of a single recreation facility type."""
    name: str = ""
    quality: float = 1.0       # 0-1, degrades over time
    usage_rate: float = 0.5    # Fraction of crew using per week
    maintenance_debt: float = 0.0
    last_overhaul_year: float = 0.0


@dataclass
class RecreationMoraleState:
    """Full recreation and morale tracking."""
    # VR systems
    vr_headset_count: int = 30              # ESTIMATE — 60% of 50-person crew (1 headset per 2 people)
    vr_headsets_functional: int = 30
    vr_environment_library_size: int = 200  # ESTIMATE — 200 distinct environments (Palinkas 2001 analogue)
    vr_novelty_factor: float = 1.0          # Decays as crew exhausts content
    vr_hardware_age_years: float = 0.0

    # Sports facilities
    sports_facilities: list[RecreationFacility] = field(
        default_factory=lambda: [
            RecreationFacility(name="gymnasium", quality=1.0, usage_rate=0.8),
            RecreationFacility(name="swimming_pool", quality=1.0, usage_rate=0.5),
            RecreationFacility(name="sports_court", quality=1.0, usage_rate=0.6),
            RecreationFacility(name="running_track", quality=1.0, usage_rate=0.7),
        ]
    )

    # Arts and culture
    instrument_count: int = 50              # ESTIMATE — 1 instrument per person for full crew
    instruments_playable: int = 50
    theater_productions_per_year: int = 4   # ESTIMATE — quarterly productions (Kanas 2015 analogue)
    art_supplies_remaining: float = 1.0     # 0-1, fraction of initial stock

    # Library
    digital_library_intact: float = 1.0    # Bit rot fraction remaining
    physical_books_count: int = 5000        # ESTIMATE — ~100 books/person (NASA lunar library analogue)
    glass_archive_health: float = 1.0       # Fused silica archival disks: >10⁶ yr durability (Shimotsuma 2021)

    # Gardens (decorative, not agricultural)
    garden_area_m2: float = 200.0           # ESTIMATE — 4 m²/person decorative space (O'Neill 1977 §8)
    garden_health: float = 1.0
    garden_biodiversity: float = 1.0

    # Social calendar
    festivals_per_year: int = 12            # ESTIMATE — monthly festivals for crew cohesion (Kanas 2015 analogue)
    community_participation_rate: float = 0.8  # ESTIMATE — 80% participation (Mars-500 analogue)

    # Exercise compliance
    exercise_compliance_rate: float = 0.9  # ESTIMATE — ISS: 2 hr/day mandatory; ~90% compliance (Loehr 2015 NASA TM-2015-218576)
    bone_density_modifier: float = 1.0     # 1.0 = normal

    # Aggregate morale
    crew_morale: float = 0.85  # ESTIMATE — 0.85 initial (Mars-500 study: 0.8-0.9 range; Shved 2011)
    boredom_index: float = 0.1  # ESTIMATE — low baseline boredom (Palinkas 2001 onset ~0.1 yr)

    # History
    years_without_major_event: int = 0
    morale_trend: float = 0.0  # Positive = improving, negative = declining


class RecreationMoraleSimulator:
    """Simulates recreation facilities, cultural activities, and crew morale.

    Morale is the hidden variable that drives everything: productivity,
    conflict rate, cooperation, birth rate decisions, even suicide risk.
    Recreation is not a luxury on a generation ship — it is infrastructure.
    """

    VR_HARDWARE_LIFETIME_YEARS = 5
    INSTRUMENT_LIFETIME_YEARS = 50  # Well-maintained instruments last decades

    def __init__(self, crew_size: int = 50, seed: int | None = None) -> None:
        self._rng = random.Random(seed)
        self.crew_size = crew_size
        self.state = RecreationMoraleState()

    def simulate_year(self, mission_year: float) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []
        s = self.state

        # --- VR system degradation ---
        s.vr_hardware_age_years += 1.0
        if s.vr_hardware_age_years >= self.VR_HARDWARE_LIFETIME_YEARS:
            # Replace cycle — not all units replaced at once
            units_replaced = max(1, s.vr_headset_count // 3)
            s.vr_headsets_functional = min(
                s.vr_headset_count,
                s.vr_headsets_functional + units_replaced
            )
            s.vr_hardware_age_years = 0.0
            events.append({
                "year": mission_year, "severity": "NOMINAL",
                "message": (
                    f"VR hardware refresh — {units_replaced} headsets "
                    "replaced from manufacturing"
                ),
                "subsystem": "recreation",
            })
        else:
            # Ongoing degradation: radiation bit-flips, lens scratching, OLED burn-in
            failure_rate = 0.03 + 0.01 * s.vr_hardware_age_years
            for _ in range(s.vr_headsets_functional):
                if self._rng.random() < failure_rate:
                    s.vr_headsets_functional = max(0, s.vr_headsets_functional - 1)

        # VR novelty decays as crew exhausts content library
        content_exhaustion = min(1.0, mission_year * self.crew_size / (
            s.vr_environment_library_size * 50
        ))
        # New content created by crew partially offsets exhaustion
        crew_content_creation = 0.02 * mission_year
        s.vr_novelty_factor = max(
            0.2, 1.0 - content_exhaustion + min(0.3, crew_content_creation * 0.01)
        )

        # --- Sports facility degradation ---
        for fac in s.sports_facilities:
            wear = fac.usage_rate * 0.02 + self._rng.gauss(0, 0.005)
            fac.quality = max(0.1, fac.quality - abs(wear))
            fac.maintenance_debt += abs(wear)

            # Overhaul every 10 years
            if mission_year - fac.last_overhaul_year >= 10:
                fac.quality = min(1.0, fac.quality + 0.5)
                fac.maintenance_debt = max(0, fac.maintenance_debt - 0.3)
                fac.last_overhaul_year = mission_year

        # --- Instruments ---
        for _ in range(s.instruments_playable):
            if self._rng.random() < 1.0 / self.INSTRUMENT_LIFETIME_YEARS:
                s.instruments_playable = max(0, s.instruments_playable - 1)
        # Some instruments manufactured as replacements
        if s.instruments_playable < s.instrument_count * 0.7:
            crafted = self._rng.randint(1, 3)
            s.instruments_playable = min(
                s.instrument_count, s.instruments_playable + crafted
            )

        # --- Art supplies depletion ---
        s.art_supplies_remaining = max(
            0, s.art_supplies_remaining - 0.02 - self._rng.uniform(0, 0.005)
        )
        # Recycling and manufacturing partially replenish
        if s.art_supplies_remaining < 0.3:
            s.art_supplies_remaining += 0.1  # Manufacturing run

        # --- Library maintenance ---
        # Digital: bit rot from radiation
        s.digital_library_intact = max(
            0.5, s.digital_library_intact - 0.001 * (1 + 0.0005 * mission_year)
        )
        # Physical books degrade slowly in controlled atmosphere
        if self._rng.random() < 0.01:
            s.physical_books_count = max(0, s.physical_books_count - self._rng.randint(1, 5))
        # Glass archive is essentially permanent
        s.glass_archive_health = max(0.99, s.glass_archive_health - 0.0001)

        # --- Gardens ---
        s.garden_health = max(
            0.3, s.garden_health - 0.01 + self._rng.gauss(0, 0.005)
        )
        s.garden_biodiversity = max(
            0.2, s.garden_biodiversity - 0.003 + self._rng.gauss(0, 0.002)
        )

        # --- Exercise compliance ---
        # Compliance drifts based on morale and boredom
        compliance_drift = self._rng.gauss(0, 0.02) + 0.01 * (s.crew_morale - 0.5)
        s.exercise_compliance_rate = max(
            0.3, min(1.0, s.exercise_compliance_rate + compliance_drift)
        )
        # Bone density: 0.56g causes ~0.5%/month loss without exercise
        base_loss_yr = 0.06  # 6% per year at 0.56g without exercise
        exercise_protection = s.exercise_compliance_rate * 0.9  # 90% protection max
        s.bone_density_modifier = max(
            0.5, s.bone_density_modifier - base_loss_yr * (1 - exercise_protection)
        )

        # --- Community events ---
        if self._rng.random() < 0.05:
            # Special event: wedding, birth celebration, memorial
            s.years_without_major_event = 0
            events.append({
                "year": mission_year, "severity": "NOMINAL",
                "message": "Community celebration event — morale boost",
                "subsystem": "recreation",
            })
        else:
            s.years_without_major_event += 1

        # --- Aggregate morale calculation ---
        vr_morale = (
            s.vr_headsets_functional / max(1, s.vr_headset_count)
            * s.vr_novelty_factor
        )
        sports_morale = sum(f.quality for f in s.sports_facilities) / len(
            s.sports_facilities
        )
        arts_morale = (
            s.instruments_playable / max(1, s.instrument_count) * 0.5
            + s.art_supplies_remaining * 0.3
            + min(1.0, s.theater_productions_per_year / 4) * 0.2
        )
        garden_morale = s.garden_health * s.garden_biodiversity
        community_morale = (
            s.community_participation_rate * 0.6
            + (1.0 if s.years_without_major_event < 3 else 0.5) * 0.4
        )
        library_morale = (
            s.digital_library_intact * 0.4
            + min(1.0, s.physical_books_count / 5000) * 0.2
            + s.glass_archive_health * 0.4
        )

        raw_morale = (
            vr_morale * 0.20
            + sports_morale * 0.20
            + arts_morale * 0.15
            + garden_morale * 0.15
            + community_morale * 0.15
            + library_morale * 0.10
            + s.exercise_compliance_rate * 0.05
        )

        # Boredom accumulates over time, countered by novelty
        s.boredom_index = min(1.0, max(0, s.boredom_index + 0.01 - s.vr_novelty_factor * 0.008))
        boredom_penalty = s.boredom_index * 0.15

        s.morale_trend = raw_morale - boredom_penalty - s.crew_morale
        s.crew_morale = max(0.1, min(1.0, s.crew_morale + s.morale_trend * 0.3))

        # --- Events (latched with hysteresis) ---
        if s.crew_morale < 0.3:
            if not getattr(self, "_morale_emer_latched", False):
                events.append({
                    "year": mission_year, "severity": "EMERGENCY",
                    "message": (
                        f"Crew morale critical: {s.crew_morale:.0%} — "
                        "risk of social unrest, depression epidemic"
                    ),
                    "subsystem": "recreation",
                })
                self._morale_emer_latched = True
                self._morale_warn_latched = False
        elif s.crew_morale < 0.5:
            self._morale_emer_latched = False
            if not getattr(self, "_morale_warn_latched", False):
                events.append({
                    "year": mission_year, "severity": "WARNING",
                    "message": (
                        f"Crew morale low: {s.crew_morale:.0%} — "
                        "increase recreation investment"
                    ),
                    "subsystem": "recreation",
                })
                self._morale_warn_latched = True
        else:
            self._morale_emer_latched = False
            self._morale_warn_latched = False

        if (s.vr_headsets_functional < s.vr_headset_count * 0.3
                and not getattr(self, "_vr_low_latched", False)):
            events.append({
                "year": mission_year, "severity": "CRITICAL",
                "message": (
                    f"VR systems failing: {s.vr_headsets_functional}/"
                    f"{s.vr_headset_count} functional — "
                    "primary boredom countermeasure degraded"
                ),
                "subsystem": "recreation",
            })
            self._vr_low_latched = True
        elif s.vr_headsets_functional >= s.vr_headset_count * 0.4:
            self._vr_low_latched = False

        if s.bone_density_modifier < 0.7:
            events.append({
                "year": mission_year, "severity": "WARNING",
                "message": (
                    f"Crew bone density at {s.bone_density_modifier:.0%} — "
                    f"exercise compliance {s.exercise_compliance_rate:.0%}"
                ),
                "subsystem": "recreation",
            })

        if s.boredom_index > 0.7:
            events.append({
                "year": mission_year, "severity": "WARNING",
                "message": (
                    f"Chronic boredom index {s.boredom_index:.2f} — "
                    "need new content and activities"
                ),
                "subsystem": "recreation",
            })

        return events


# ════════════════════════════════════════════════════════════════
#  3. SUPPLY CHAIN & INVENTORY
# ════════════════════════════════════════════════════════════════

@dataclass
class InventoryItem:
    """A single tracked consumable or part category."""
    name: str = ""
    category: str = ""
    quantity: float = 0.0
    unit: str = "units"
    depletion_rate_per_year: float = 0.0
    reorder_point: float = 0.0          # When to trigger manufacturing
    manufacturing_lead_time_days: float = 7.0
    substitution_available: bool = False
    substitution_name: str = ""
    substitution_efficiency: float = 0.8  # How well substitute performs
    priority: int = 1                     # 1=life-critical, 2=important, 3=convenience
    last_audit_year: float = 0.0
    cumulative_consumed: float = 0.0
    historical_rates: list[float] = field(default_factory=list)


@dataclass
class SupplyChainState:
    """Full inventory and supply chain state."""
    items: dict[str, InventoryItem] = field(default_factory=dict)
    manufacturing_capacity: float = 1.0    # 0-1
    feedstock_metal_kg: float = 5000.0    # ESTIMATE — 5 t metal feedstock reserve (Ti alloy + Al)
    feedstock_polymer_kg: float = 3000.0  # ESTIMATE — 3 t polymer feedstock (PEEK + PLA blend)
    feedstock_chemical_kg: float = 2000.0  # ESTIMATE — 2 t chemical feedstock (solvents + reagents)
    printer_health: float = 1.0            # 3D printer fleet health
    total_items_tracked: int = 0
    critical_shortage_count: int = 0
    items_below_reorder: int = 0
    audit_discrepancy_rate: float = 0.0
    years_of_supply_remaining: float = 100.0  # Estimated
    allocation_mode: str = "normal"       # normal | rationing | emergency


# Default inventory catalog for a generation ship
_DEFAULT_INVENTORY: list[dict[str, Any]] = [
    # Medical (priority 1)
    {"name": "antibiotics_doses", "category": "medical", "quantity": 10000,
     "unit": "doses", "depletion_rate_per_year": 200, "reorder_point": 2000,
     "manufacturing_lead_time_days": 30, "priority": 1},
    {"name": "surgical_supplies", "category": "medical", "quantity": 5000,
     "unit": "kits", "depletion_rate_per_year": 100, "reorder_point": 1000,
     "manufacturing_lead_time_days": 14, "priority": 1},
    {"name": "radiation_medication", "category": "medical", "quantity": 2000,
     "unit": "doses", "depletion_rate_per_year": 20, "reorder_point": 500,
     "manufacturing_lead_time_days": 45, "priority": 1},

    # Mechanical (priority 2)
    {"name": "bearing_assemblies", "category": "mechanical", "quantity": 500,
     "unit": "units", "depletion_rate_per_year": 30, "reorder_point": 100,
     "manufacturing_lead_time_days": 3, "priority": 2,
     "substitution_available": True, "substitution_name": "bushing_sleeves"},
    {"name": "seals_and_gaskets", "category": "mechanical", "quantity": 2000,
     "unit": "units", "depletion_rate_per_year": 80, "reorder_point": 400,
     "manufacturing_lead_time_days": 1, "priority": 2},
    {"name": "fasteners_assorted", "category": "mechanical", "quantity": 50000,
     "unit": "units", "depletion_rate_per_year": 2000, "reorder_point": 10000,
     "manufacturing_lead_time_days": 0.5, "priority": 3},

    # Electronic (priority 2)
    {"name": "circuit_boards", "category": "electronic", "quantity": 300,
     "unit": "units", "depletion_rate_per_year": 15, "reorder_point": 50,
     "manufacturing_lead_time_days": 7, "priority": 2},
    {"name": "sensor_modules", "category": "electronic", "quantity": 200,
     "unit": "units", "depletion_rate_per_year": 10, "reorder_point": 40,
     "manufacturing_lead_time_days": 5, "priority": 2},

    # Raw materials (priority 1 - feedstock)
    {"name": "water_reserves_liters", "category": "raw_material", "quantity": 100000,
     "unit": "liters", "depletion_rate_per_year": 500, "reorder_point": 20000,
     "manufacturing_lead_time_days": 0, "priority": 1},

    # Food stores (priority 1)
    {"name": "preserved_food_rations", "category": "food", "quantity": 50000,
     "unit": "meals", "depletion_rate_per_year": 18250, "reorder_point": 9000,
     "manufacturing_lead_time_days": 0, "priority": 1},

    # Fuel (priority 1)
    {"name": "deuterium_fuel_kg", "category": "fuel", "quantity": 10000,
     "unit": "kg", "depletion_rate_per_year": 5, "reorder_point": 1000,
     "manufacturing_lead_time_days": 0, "priority": 1},

    # Filters and consumables (priority 1)
    {"name": "hepa_filters", "category": "consumable", "quantity": 200,
     "unit": "units", "depletion_rate_per_year": 16, "reorder_point": 32,
     "manufacturing_lead_time_days": 2, "priority": 1},
    {"name": "activated_carbon_kg", "category": "consumable", "quantity": 1000,
     "unit": "kg", "depletion_rate_per_year": 50, "reorder_point": 200,
     "manufacturing_lead_time_days": 10, "priority": 1},

    # Non-lethal security (priority 3)
    {"name": "nonlethal_rounds", "category": "ammunition", "quantity": 5000,
     "unit": "rounds", "depletion_rate_per_year": 50, "reorder_point": 500,
     "manufacturing_lead_time_days": 1, "priority": 3},
]


class SupplyChainSimulator:
    """Simulates consumable tracking, depletion, manufacturing, and allocation.

    On a generation ship there is no resupply. Everything is either:
    1. Stored from launch (finite, eventually runs out)
    2. Manufactured onboard (limited by feedstock and printer capacity)
    3. Recycled (imperfect, always some loss)

    The critical path — whichever item runs out first — determines
    mission viability. This simulator tracks that constraint.
    """

    AUDIT_INTERVAL_YEARS = 1

    def __init__(
        self,
        crew_size: int = 50,
        seed: int | None = None,
        custom_inventory: list[dict[str, Any]] | None = None,
    ) -> None:
        self._rng = random.Random(seed)
        self.crew_size = crew_size
        self.state = SupplyChainState()
        self._init_inventory(custom_inventory or _DEFAULT_INVENTORY)

    def _init_inventory(self, catalog: list[dict[str, Any]]) -> None:
        for spec in catalog:
            item = InventoryItem(
                name=spec["name"],
                category=spec.get("category", "general"),
                quantity=spec.get("quantity", 0),
                unit=spec.get("unit", "units"),
                depletion_rate_per_year=spec.get("depletion_rate_per_year", 0),
                reorder_point=spec.get("reorder_point", 0),
                manufacturing_lead_time_days=spec.get(
                    "manufacturing_lead_time_days", 7
                ),
                substitution_available=spec.get("substitution_available", False),
                substitution_name=spec.get("substitution_name", ""),
                substitution_efficiency=spec.get("substitution_efficiency", 0.8),
                priority=spec.get("priority", 2),
            )
            self.state.items[item.name] = item
        self.state.total_items_tracked = len(self.state.items)

    def simulate_year(self, mission_year: float) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []
        s = self.state

        # --- 3D printer degradation ---
        s.printer_health = max(
            0.2, s.printer_health - 0.005 - self._rng.uniform(0, 0.002)
        )
        s.manufacturing_capacity = s.printer_health * min(
            1.0,
            s.feedstock_metal_kg / 1000,
            s.feedstock_polymer_kg / 500,
        )

        # --- Deplete each item ---
        critical_count = 0
        below_reorder = 0
        min_years_remaining = float("inf")
        critical_item_name = ""

        for item in s.items.values():
            # Stochastic consumption: base rate + noise + crew size scaling
            crew_factor = self.crew_size / 50.0
            consumption = (
                item.depletion_rate_per_year * crew_factor
                * (1.0 + self._rng.gauss(0, 0.05))
            )
            consumption = max(0, consumption)

            # Rationing reduces consumption
            if s.allocation_mode == "rationing":
                if item.priority >= 3:
                    consumption *= 0.5
                elif item.priority == 2:
                    consumption *= 0.8
            elif s.allocation_mode == "emergency":
                if item.priority >= 3:
                    consumption *= 0.1
                elif item.priority == 2:
                    consumption *= 0.5

            item.quantity = max(0, item.quantity - consumption)
            item.cumulative_consumed += consumption
            item.historical_rates.append(consumption)
            # Keep last 20 years of history
            if len(item.historical_rates) > 20:
                item.historical_rates = item.historical_rates[-20:]

            # Manufacturing resupply for items that can be made
            if (
                item.quantity < item.reorder_point
                and item.manufacturing_lead_time_days > 0
                and s.manufacturing_capacity > 0.3
            ):
                # Produce based on capacity and lead time
                production_rate = (
                    365.0 / max(1, item.manufacturing_lead_time_days)
                    * s.manufacturing_capacity * 0.3
                )
                produced = min(production_rate, item.reorder_point - item.quantity)
                if produced > 0:
                    item.quantity += produced
                    # Feedstock consumption per manufactured unit.
                    # Based on the item's own ``mass_per_unit_kg``
                    # field with a 50/30 metal/polymer split
                    # typical of ISS spare parts (NASA/TM-2018-219855
                    # "In-Space Manufacturing" Table 2). Previously
                    # hard-coded to 0.1 kg/unit which over- or
                    # under-counted material draw depending on the
                    # item mass.
                    unit_mass = getattr(item, "mass_per_unit_kg", 0.1)
                    s.feedstock_metal_kg = max(
                        0.0, s.feedstock_metal_kg - produced * unit_mass * 0.5
                    )
                    s.feedstock_polymer_kg = max(
                        0.0, s.feedstock_polymer_kg - produced * unit_mass * 0.3
                    )

            # Track critical status (latched per-item to avoid yearly spam)
            if not hasattr(self, "_stockout_latched"):
                self._stockout_latched = set()
            if not hasattr(self, "_reorder_latched"):
                self._reorder_latched = set()
            if item.quantity <= 0:
                critical_count += 1
                if item.priority == 1 and item.name not in self._stockout_latched:
                    events.append({
                        "year": mission_year, "severity": "EMERGENCY",
                        "message": (
                            f"STOCKOUT: {item.name} — zero remaining. "
                            f"Priority {item.priority} "
                            f"({'life-critical' if item.priority == 1 else 'important'})"
                        ),
                        "subsystem": "supply_chain",
                    })
                    self._stockout_latched.add(item.name)
            else:
                self._stockout_latched.discard(item.name)
                if item.quantity < item.reorder_point:
                    below_reorder += 1
                    if item.priority == 1 and item.name not in self._reorder_latched:
                        events.append({
                            "year": mission_year, "severity": "WARNING",
                            "message": (
                                f"{item.name} below reorder: {item.quantity:.0f} "
                                f"{item.unit} (reorder at {item.reorder_point:.0f})"
                            ),
                            "subsystem": "supply_chain",
                        })
                        self._reorder_latched.add(item.name)
                elif item.quantity >= item.reorder_point * 1.5:
                    self._reorder_latched.discard(item.name)

            # Years remaining for this item
            if item.depletion_rate_per_year > 0:
                yrs = item.quantity / (item.depletion_rate_per_year * crew_factor)
                if yrs < min_years_remaining:
                    min_years_remaining = yrs
                    critical_item_name = item.name

        s.critical_shortage_count = critical_count
        s.items_below_reorder = below_reorder
        s.years_of_supply_remaining = (
            min_years_remaining if min_years_remaining < float("inf") else 999
        )

        # --- Annual audit ---
        if mission_year % self.AUDIT_INTERVAL_YEARS < 1:
            discrepancies = 0
            for item in s.items.values():
                # Simulate audit: small chance of finding discrepancy
                if self._rng.random() < 0.05:
                    discrepancy_pct = self._rng.uniform(0.01, 0.05)
                    item.quantity *= (1 - discrepancy_pct)
                    discrepancies += 1
                item.last_audit_year = mission_year
            s.audit_discrepancy_rate = discrepancies / max(1, s.total_items_tracked)
            if discrepancies > 0:
                events.append({
                    "year": mission_year, "severity": "NOMINAL",
                    "message": (
                        f"Annual audit: {discrepancies} discrepancies found "
                        f"across {s.total_items_tracked} item categories"
                    ),
                    "subsystem": "supply_chain",
                })

        # --- Allocation mode changes ---
        if s.years_of_supply_remaining < 2 and s.allocation_mode == "normal":
            s.allocation_mode = "rationing"
            events.append({
                "year": mission_year, "severity": "CRITICAL",
                "message": (
                    f"RATIONING activated — critical path item "
                    f"'{critical_item_name}' at "
                    f"{s.years_of_supply_remaining:.1f} years supply"
                ),
                "subsystem": "supply_chain",
            })
        elif s.years_of_supply_remaining < 0.5 and s.allocation_mode != "emergency":
            s.allocation_mode = "emergency"
            events.append({
                "year": mission_year, "severity": "EMERGENCY",
                "message": (
                    f"EMERGENCY allocation — '{critical_item_name}' "
                    f"at {s.years_of_supply_remaining:.2f} years. "
                    "Non-essential consumption halted."
                ),
                "subsystem": "supply_chain",
            })
        elif s.years_of_supply_remaining > 5 and s.allocation_mode != "normal":
            s.allocation_mode = "normal"
            events.append({
                "year": mission_year, "severity": "NOMINAL",
                "message": "Supply levels restored — normal allocation resumed",
                "subsystem": "supply_chain",
            })

        # --- Feedstock warnings (latched) ---
        if s.feedstock_metal_kg < 500 and not getattr(self, "_metal_low_latched", False):
            events.append({
                "year": mission_year, "severity": "CRITICAL",
                "message": (
                    f"Metal feedstock low: {s.feedstock_metal_kg:.0f} kg — "
                    "manufacturing capacity will collapse"
                ),
                "subsystem": "supply_chain",
            })
            self._metal_low_latched = True
        elif s.feedstock_metal_kg >= 750:
            self._metal_low_latched = False

        if s.feedstock_polymer_kg < 300 and not getattr(self, "_polymer_low_latched", False):
            events.append({
                "year": mission_year, "severity": "CRITICAL",
                "message": (
                    f"Polymer feedstock low: {s.feedstock_polymer_kg:.0f} kg — "
                    "3D printing limited"
                ),
                "subsystem": "supply_chain",
            })
            self._polymer_low_latched = True
        elif s.feedstock_polymer_kg >= 450:
            self._polymer_low_latched = False

        # --- Printer health (latched) ---
        if s.printer_health < 0.4 and not getattr(self, "_sc_printer_latched", False):
            events.append({
                "year": mission_year, "severity": "WARNING",
                "message": (
                    f"3D printer fleet health {s.printer_health:.0%} — "
                    "manufacturing throughput degraded"
                ),
                "subsystem": "supply_chain",
            })
            self._sc_printer_latched = True
        elif s.printer_health >= 0.5:
            self._sc_printer_latched = False

        return events

    def get_critical_path(self) -> tuple[str, float]:
        """Return the item name and years until stockout for the critical path."""
        min_years = float("inf")
        critical = ""
        crew_factor = self.crew_size / 50.0
        for item in self.state.items.values():
            if item.depletion_rate_per_year > 0:
                yrs = item.quantity / (item.depletion_rate_per_year * crew_factor)
                if yrs < min_years:
                    min_years = yrs
                    critical = item.name
        return critical, min_years

    def get_category_summary(self) -> dict[str, dict[str, float]]:
        """Return summary statistics grouped by inventory category."""
        summary: dict[str, dict[str, float]] = {}
        for item in self.state.items.values():
            cat = item.category
            if cat not in summary:
                summary[cat] = {"total_quantity": 0, "total_consumed": 0, "count": 0}
            summary[cat]["total_quantity"] += item.quantity
            summary[cat]["total_consumed"] += item.cumulative_consumed
            summary[cat]["count"] += 1
        return summary


# ════════════════════════════════════════════════════════════════
#  ORCHESTRATOR — runs all three habitat systems together
# ════════════════════════════════════════════════════════════════

class HabitatSystemsOrchestrator:
    """Runs Environmental Control, Recreation & Morale, and Supply Chain
    together with cross-system feedback loops.

    Cross-system interactions:
    - ECLSS filter consumption feeds supply chain depletion
    - Supply chain shortages of filters degrade ECLSS performance
    - ECLSS temperature/air quality affects morale
    - Low morale reduces exercise compliance (recreation -> ECLSS bone density)
    - Manufacturing feedstock depletion limits ECLSS part replacement
    """

    def __init__(self, crew_size: int = 50, seed: int | None = None) -> None:
        self.crew_size = crew_size
        self.eclss = EnvironmentalControlSimulator(crew_size=crew_size, seed=seed)
        self.recreation = RecreationMoraleSimulator(
            crew_size=crew_size,
            seed=seed + 1 if seed is not None else None,
        )
        self.supply_chain = SupplyChainSimulator(
            crew_size=crew_size,
            seed=seed + 2 if seed is not None else None,
        )

    def simulate_year(self, mission_year: float) -> list[dict[str, Any]]:
        events: list[dict[str, Any]] = []

        # Run subsystems
        events.extend(self.eclss.simulate_year(mission_year))
        events.extend(self.recreation.simulate_year(mission_year))
        events.extend(self.supply_chain.simulate_year(mission_year))

        # --- Cross-system feedback ---
        eclss_s = self.eclss.state
        rec_s = self.recreation.state
        sc_s = self.supply_chain.state

        # ECLSS air quality affects morale
        if eclss_s.habitat_zone.co2_ppm > 1000:
            co2_penalty = (eclss_s.habitat_zone.co2_ppm - 1000) / 5000
            rec_s.crew_morale = max(0.1, rec_s.crew_morale - co2_penalty)

        # Temperature discomfort affects morale
        temp_deviation = abs(
            eclss_s.habitat_zone.temperature_c
            - eclss_s.habitat_zone.target_temp_c
        )
        if temp_deviation > 3:
            rec_s.crew_morale = max(
                0.1, rec_s.crew_morale - temp_deviation * 0.01
            )

        # Low morale reduces exercise compliance
        if rec_s.crew_morale < 0.4:
            rec_s.exercise_compliance_rate = max(
                0.3, rec_s.exercise_compliance_rate - 0.05
            )

        # Supply chain filter stock affects ECLSS (latched)
        hepa_item = sc_s.items.get("hepa_filters")
        if hepa_item and hepa_item.quantity <= 0:
            eclss_s.hepa_filter_health = max(
                0.1, eclss_s.hepa_filter_health - 0.1
            )
            if not getattr(self, "_hepa_zero_latched", False):
                events.append({
                    "year": mission_year, "severity": "CRITICAL",
                    "message": (
                        "No HEPA filter stock — ECLSS air filtration degrading"
                    ),
                    "subsystem": "habitat_crosslink",
                })
                self._hepa_zero_latched = True
        elif hepa_item and hepa_item.quantity > 0:
            self._hepa_zero_latched = False

        carbon_item = sc_s.items.get("activated_carbon_kg")
        if carbon_item and carbon_item.quantity <= 0:
            eclss_s.activated_carbon_capacity = max(
                0.1, eclss_s.activated_carbon_capacity - 0.1
            )

        return events
