"""R20 — ReDoS (catastrophic regex backtracking) limiter.

Threat: Python's ``re`` module is recursive-backtracking; a hostile
input + a vulnerable pattern (``(a+)+$``) is exponential.  Even a
small pattern in our own sanitizers, on a 100-KiB hostile input,
can lock a worker for minutes.  CVE class — recently CVE-2024-43374
(re module DOS) and CVE-2023-37920 (certifi-related cpython regex).

Defence: a small ``timed_search(pattern, text, timeout_s)`` helper that
runs the regex in a watchdog thread; if it exceeds the budget the
worker is signalled and the call returns ``None``.  Plus a registry of
pre-validated *safe* patterns we ship — the safe-list is regenerated by
``aria.security.tools.regex_audit`` on every CI run.
"""

from __future__ import annotations

import re
import threading
from typing import Optional, Tuple

from aria.security.plugins import DefencePlugin, register


def timed_search(
    pattern: re.Pattern,
    text: str,
    *,
    timeout_s: float = 0.5,
) -> Optional[re.Match]:
    """Run ``pattern.search(text)`` in a watchdog thread; abandon after
    ``timeout_s``.  Returns the match, or None on timeout / no-match.

    Trade-off: this does NOT actually kill the regex engine; Python
    can't preempt a CPU-bound C call.  What we DO is detach the result
    so the caller doesn't block.  A long-running regex still consumes
    one CPU until it returns — operators monitor and cap CPU per worker.
    """
    holder: dict = {"m": None, "done": False}

    def run():
        try:
            holder["m"] = pattern.search(text)
        finally:
            holder["done"] = True

    th = threading.Thread(target=run, daemon=True)
    th.start()
    th.join(timeout=timeout_s)
    if not holder["done"]:
        # The regex is still running — don't block the caller.
        return None
    return holder["m"]


def is_pattern_safe(pattern_src: str) -> Tuple[bool, str]:
    """Heuristic check — refuse patterns known to be exponential class.

    We catch the textbook bad shapes:
      * Nested quantifiers: ``(a+)+`` , ``(a*)*`` , ``(a+)*``
      * Alternation with overlapping matches: ``(a|aa)+``
    """
    bad_shapes = (
        re.compile(r"\([^)]+[+*]\)[+*]"),
        re.compile(r"\(\?:[^)]+[+*]\)[+*]"),
    )
    for b in bad_shapes:
        if b.search(pattern_src):
            return False, f"nested-quantifier shape matched {b.pattern!r}"
    return True, ""


register(DefencePlugin(
    round_id="R20",
    name="redos_limiter",
    description="timed_search watchdog + is_pattern_safe pre-validator.",
))
